const A2_WORDS = [
    // ===== NOUNS =====
    { word: "Erfolg", article: "der", meaning: "success", category: "work & profession" },
    { word: "Fehler", article: "der", meaning: "mistake", category: "school & education" },
    { word: "Grund", article: "der", meaning: "reason", category: "communication & media" },
    { word: "Ort", article: "der", meaning: "place", category: "city & places" },
    { word: "Wunsch", article: "der", meaning: "wish", category: "emotions & adjectives" },
    { word: "Müll", article: "der", meaning: "trash", category: "house & furniture" },
    { word: "Zweifel", article: "der", meaning: "doubt", category: "emotions & adjectives" },
    { word: "Vertrag", article: "der", meaning: "contract", category: "work & profession" },
    { word: "Lohn", article: "der", meaning: "wage / salary", category: "work & profession" },
    { word: "Zuschauer", article: "der", meaning: "spectator", category: "hobbies & sports" },
    { word: "Kunde", article: "der", meaning: "customer", category: "shopping & money" },
    { word: "Bildschirm", article: "der", meaning: "screen", category: "communication & media" },
    { word: "Drucker", article: "der", meaning: "printer", category: "work & profession" },
    { word: "Verkehr", article: "der", meaning: "traffic", category: "transportation" },
    { word: "Anfang", article: "der", meaning: "beginning", category: "time & calendar" },
    
    { word: "Meinung", article: "die", meaning: "opinion", category: "communication & media" },
    { word: "Entscheidung", article: "die", meaning: "decision", category: "daily life & objects" },
    { word: "Erfahrung", article: "die", meaning: "experience", category: "school & education" },
    { word: "Wahrheit", article: "die", meaning: "truth", category: "communication & media" },
    { word: "Krankheit", article: "die", meaning: "illness", category: "body & health" },
    { word: "Möglichkeit", article: "die", meaning: "possibility", category: "daily life & objects" },
    { word: "Regel", article: "die", meaning: "rule", category: "school & education" },
    { word: "Angst", article: "die", meaning: "fear", category: "emotions & adjectives" },
    { word: "Bedeutung", article: "die", meaning: "meaning", category: "school & education" },
    { word: "Grenze", article: "die", meaning: "border / limit", category: "travel & vacation" },
    { word: "Umwelt", article: "die", meaning: "environment", category: "nature & weather" },
    { word: "Wirtschaft", article: "die", meaning: "economy", category: "work & profession" },
    { word: "Zukunft", article: "die", meaning: "future", category: "time & calendar" },
    { word: "Sicherheit", article: "die", meaning: "security", category: "daily life & objects" },
    { word: "Gesundheit", article: "die", meaning: "health", category: "body & health" },

    { word: "Ziel", article: "das", meaning: "goal", category: "school & education" },
    { word: "Ergebnis", article: "das", meaning: "result", category: "school & education" },
    { word: "Gesetz", article: "das", meaning: "law", category: "work & profession" },
    { word: "Gefühl", article: "das", meaning: "feeling", category: "emotions & adjectives" },
    { word: "Gespräch", article: "das", meaning: "conversation", category: "communication & media" },
    { word: "Thema", article: "das", meaning: "topic", category: "communication & media" },
    { word: "Angebot", article: "das", meaning: "offer", category: "shopping & money" },
    { word: "Verhalten", article: "das", meaning: "behavior", category: "daily life & objects" },
    { word: "Geheimnis", article: "das", meaning: "secret", category: "communication & media" },
    { word: "Gerät", article: "das", meaning: "device", category: "communication & media" },
    { word: "Werkzeug", article: "das", meaning: "tool", category: "work & profession" },
    { word: "Zeichen", article: "das", meaning: "sign", category: "communication & media" },
    { word: "Mitglied", article: "das", meaning: "member", category: "family & people" },
    { word: "System", article: "das", meaning: "system", category: "work & profession" },
    { word: "Interesse", article: "das", meaning: "interest", category: "hobbies & sports" },

    // ===== VERBS =====
    { word: "erinnern", meaning: "to remember", category: "verbs", type: "verb" },
    { word: "entscheiden", meaning: "to decide", category: "verbs", type: "verb" },
    { word: "erzählen", meaning: "to tell / narrate", category: "verbs", type: "verb" },
    { word: "versprechen", meaning: "to promise", category: "verbs", type: "verb" },
    { word: "erwarten", meaning: "to expect", category: "verbs", type: "verb" },
    { word: "passieren", meaning: "to happen", category: "verbs", type: "verb" },
    { word: "bemerken", meaning: "to notice", category: "verbs", type: "verb" },
    { word: "erreichen", meaning: "to achieve / reach", category: "verbs", type: "verb" },
    { word: "überlegen", meaning: "to consider / think over", category: "verbs", type: "verb" },
    { word: "verlassen", meaning: "to leave", category: "verbs", type: "verb" },
    { word: "anbieten", meaning: "to offer", category: "verbs", type: "verb" },
    { word: "vergleichen", meaning: "to compare", category: "verbs", type: "verb" },
    { word: "teilnehmen", meaning: "to participate", category: "verbs", type: "verb" },
    { word: "erkennen", meaning: "to recognize", category: "verbs", type: "verb" },
    { word: "bedeuten", meaning: "to mean", category: "verbs", type: "verb" },
    { word: "fehlen", meaning: "to be missing / to lack", category: "verbs", type: "verb" },
    { word: "kümmern", meaning: "to care for / look after", category: "verbs", type: "verb" },
    { word: "gehören", meaning: "to belong", category: "verbs", type: "verb" },
    { word: "streiten", meaning: "to argue", category: "verbs", type: "verb" },
    { word: "weinen", meaning: "to cry", category: "verbs", type: "verb" },

    // ===== ADJECTIVES =====
    { word: "gefährlich", meaning: "dangerous", category: "adjectives", type: "adjective" },
    { word: "vorsichtig", meaning: "careful", category: "adjectives", type: "adjective" },
    { word: "wichtig", meaning: "important", category: "adjectives", type: "adjective" },
    { word: "möglich", meaning: "possible", category: "adjectives", type: "adjective" },
    { word: "erfolgreich", meaning: "successful", category: "adjectives", type: "adjective" },
    { word: "zufrieden", meaning: "satisfied", category: "adjectives", type: "adjective" },
    { word: "verrückt", meaning: "crazy", category: "adjectives", type: "adjective" },
    { word: "streng", meaning: "strict", category: "adjectives", type: "adjective" },
    { word: "gemütlich", meaning: "cozy / comfortable", category: "adjectives", type: "adjective" },
    { word: "spannend", meaning: "exciting / thrilling", category: "adjectives", type: "adjective" },
    { word: "langweilig", meaning: "boring", category: "adjectives", type: "adjective" },
    { word: "mutig", meaning: "brave", category: "adjectives", type: "adjective" },
    { word: "stolz", meaning: "proud", category: "adjectives", type: "adjective" },
    { word: "seltsam", meaning: "strange / weird", category: "adjectives", type: "adjective" },
    { word: "leise", meaning: "quiet", category: "adjectives", type: "adjective" },

    // ===== ADVERBS =====
    { word: "besonders", meaning: "especially", category: "adverbs", type: "adverb" },
    { word: "wenigstens", meaning: "at least", category: "adverbs", type: "adverb" },
    { word: "deshalb", meaning: "therefore", category: "adverbs", type: "adverb" },
    { word: "hoffentlich", meaning: "hopefully", category: "adverbs", type: "adverb" },
    { word: "normalerweise", meaning: "normally", category: "adverbs", type: "adverb" },
    { word: "nirgends", meaning: "nowhere", category: "adverbs", type: "adverb" },
    { word: "überall", meaning: "everywhere", category: "adverbs", type: "adverb" },
    { word: "sofort", meaning: "immediately", category: "adverbs", type: "adverb" },
    { word: "plötzlich", meaning: "suddenly", category: "adverbs", type: "adverb" },
    { word: "schließlich", meaning: "finally / eventually", category: "adverbs", type: "adverb" },

    // ===== PREPOSITIONS =====
    { word: "wegen", meaning: "because of", category: "prepositions", type: "preposition" },
    { word: "trotz", meaning: "despite", category: "prepositions", type: "preposition" },
    { word: "während", meaning: "during", category: "prepositions", type: "preposition" },
    { word: "innerhalb", meaning: "inside of / within", category: "prepositions", type: "preposition" },
    { word: "außerhalb", meaning: "outside of", category: "prepositions", type: "preposition" },
    { word: "gegenüber", meaning: "opposite / across from", category: "prepositions", type: "preposition" },
    { word: "statt", meaning: "instead of", category: "prepositions", type: "preposition" },
    { word: "entlang", meaning: "along", category: "prepositions", type: "preposition" },
    { word: "neben", meaning: "next to", category: "prepositions", type: "preposition" },
    { word: "zwischen", meaning: "between", category: "prepositions", type: "preposition" },

    // ===== CONJUNCTIONS =====
    { word: "damit", meaning: "so that", category: "conjunctions", type: "conjunction" },
    { word: "ob", meaning: "whether / if", category: "conjunctions", type: "conjunction" },
    { word: "als", meaning: "when (in the past) / than", category: "conjunctions", type: "conjunction" },
    { word: "solange", meaning: "as long as", category: "conjunctions", type: "conjunction" },
    { word: "falls", meaning: "in case / if", category: "conjunctions", type: "conjunction" },
    { word: "entweder ... oder", meaning: "either ... or", category: "conjunctions", type: "conjunction" },
    { word: "weder ... noch", meaning: "neither ... nor", category: "conjunctions", type: "conjunction" },
    { word: "zwar ... aber", meaning: "indeed ... but", category: "conjunctions", type: "conjunction" },
    { word: "sowohl ... als auch", meaning: "both ... and", category: "conjunctions", type: "conjunction" },
    { word: "deswegen", meaning: "that's why", category: "conjunctions", type: "conjunction" },

    // ===== NOUNS (Batch 1) =====
    { word: "Absender", article: "der", meaning: "sender", category: "communication & media" },
    { word: "Alltag", article: "der", meaning: "everyday life", category: "daily life & objects" },
    { word: "Anschluss", article: "der", meaning: "connection", category: "transportation" },
    { underline: false, word: "Apparat", article: "der", meaning: "device / machine", category: "daily life & objects" },
    { word: "Ausgang", article: "der", meaning: "exit", category: "city & places" },
    { word: "Ausweis", article: "der", meaning: "ID card", category: "daily life & objects" },
    { word: "Beamte", article: "der", meaning: "official / civil servant", category: "work & profession" },
    { word: "Bewerber", article: "der", meaning: "applicant", category: "work & profession" },
    { word: "Bürger", article: "der", meaning: "citizen", category: "city & places" },
    { word: "Eingang", article: "der", meaning: "entrance", category: "city & places" },
    { word: "Empfänger", article: "der", meaning: "receiver / recipient", category: "communication & media" },
    { word: "Gedanke", article: "der", meaning: "thought", category: "emotions & adjectives" },
    { word: "Geschmack", article: "der", meaning: "taste", category: "food & drink" },
    { word: "Hafen", article: "der", meaning: "port / harbor", category: "transportation" },
    { word: "Hof", article: "der", meaning: "courtyard / farm", category: "city & places" },
    { word: "Inhalt", article: "der", meaning: "content", category: "school & education" },
    { word: "Kindergarten", article: "der", meaning: "kindergarten", category: "school & education" },
    { word: "Kraftrad", article: "der", meaning: "motorcycle", category: "transportation" },
    { word: "Lebenslauf", article: "der", meaning: "CV / resume", category: "work & profession" },
    { word: "Motor", article: "der", meaning: "motor / engine", category: "transportation" },
    { word: "Notarzt", article: "der", meaning: "emergency doctor", category: "body & health" },
    { word: "Notfall", article: "der", meaning: "emergency", category: "body & health" },
    { word: "Prospekt", article: "der", meaning: "brochure", category: "shopping & money" },
    { word: "Rat", article: "der", meaning: "advice", category: "communication & media" },
    { word: "Schalter", article: "der", meaning: "switch / counter", category: "daily life & objects" },
    { word: "Schatten", article: "der", meaning: "shadow", category: "nature & weather" },
    { word: "Stau", article: "der", meaning: "traffic jam", category: "transportation" },
    { word: "Teilnehmer", article: "der", meaning: "participant", category: "school & education" },
    { word: "Umzug", article: "der", meaning: "move / relocation", category: "house & furniture" },
    { word: "Verein", article: "der", meaning: "club / association", category: "hobbies & sports" },
    { word: "Verkäufer", article: "der", meaning: "seller / shop assistant", category: "shopping & money" },
    { word: "Versuch", article: "der", meaning: "attempt", category: "school & education" },
    { word: "Vorteil", article: "der", meaning: "advantage", category: "school & education" },
    { word: "Zeuge", article: "der", meaning: "witness", category: "city & places" },
    { word: "Auskunft", article: "die", meaning: "information", category: "communication & media" },
    { word: "Aussage", article: "die", meaning: "statement", category: "communication & media" },
    { word: "Auswahl", article: "die", meaning: "choice / selection", category: "shopping & money" },
    { word: "Bäckerei", article: "die", meaning: "bakery", category: "city & places" },
    { word: "Bedingung", article: "die", meaning: "condition", category: "school & education" },
    { word: "Beschwerde", article: "die", meaning: "complaint", category: "communication & media" },
    { word: "Bewerbung", article: "die", meaning: "application", category: "work & profession" },
    { word: "Decke", article: "die", meaning: "ceiling / blanket", category: "house & furniture" },
    { word: "Dose", article: "die", meaning: "can", category: "food & drink" },
    { word: "Eile", article: "die", meaning: "hurry", category: "time & calendar" },
    { word: "Einfahrt", article: "die", meaning: "driveway / entrance", category: "city & places" },
    { word: "Erlaubnis", article: "die", meaning: "permission", category: "daily life & objects" },
    { word: "Ernährung", article: "die", meaning: "nutrition", category: "food & drink" },
    { word: "Feuerwehr", article: "die", meaning: "fire department", category: "city & places" },
    { word: "Frisur", article: "die", meaning: "hairstyle", category: "body & health" },
    { word: "Garantie", article: "die", meaning: "guarantee", category: "shopping & money" },
    { word: "Gebrauchsanweisung", article: "die", meaning: "instruction manual", category: "daily life & objects" },
    { word: "Gegend", article: "die", meaning: "area / neighborhood", category: "city & places" },
    { word: "Gewohnheit", article: "die", meaning: "habit", category: "daily life & objects" },
    { word: "Heizung", article: "die", meaning: "heating", category: "house & furniture" },
    { word: "Höhe", article: "die", meaning: "height", category: "nature & weather" },
    { word: "Kasse", article: "die", meaning: "checkout / cash register", category: "shopping & money" },
    { word: "Luft", article: "die", meaning: "air", category: "nature & weather" },
    { word: "Miete", article: "die", meaning: "rent", category: "house & furniture" },
    { word: "Mitteilung", article: "die", meaning: "message / communication", category: "communication & media" },
    { word: "Natur", article: "die", meaning: "nature", category: "nature & weather" },
    { word: "Notiz", article: "die", meaning: "note", category: "communication & media" },
    { word: "Pflicht", article: "die", meaning: "duty", category: "work & profession" },
    { word: "Prüfung", article: "die", meaning: "exam", category: "school & education" },
    { word: "Richtung", article: "die", meaning: "direction", category: "travel & vacation" },
    { word: "Rücksicht", article: "die", meaning: "consideration", category: "emotions & adjectives" },
    { word: "Ruhe", article: "die", meaning: "quiet / peace", category: "emotions & adjectives" },
    { word: "Schere", article: "die", meaning: "scissors", category: "daily life & objects" },
    { word: "Schlange", article: "die", meaning: "snake / line / queue", category: "animals" },
    { word: "Sprechstunde", article: "die", meaning: "office hour", category: "work & profession" },
    { word: "Strafe", article: "die", meaning: "punishment / fine", category: "daily life & objects" },
    { word: "Stufe", article: "die", meaning: "step / level", category: "house & furniture" },
    { word: "Summe", article: "die", meaning: "sum / total", category: "numbers & quantities" },
    { word: "Tastatur", article: "die", meaning: "keyboard", category: "communication & media" },
    { word: "Unterschrift", article: "die", meaning: "signature", category: "work & profession" },
    { word: "Ursache", article: "die", meaning: "cause", category: "daily life & objects" },
    { word: "Wahl", article: "die", meaning: "choice / election", category: "daily life & objects" },
    { word: "Warnung", article: "die", meaning: "warning", category: "communication & media" },
    { word: "Zeitschrift", article: "die", meaning: "magazine", category: "communication & media" },
    { word: "Abitur", article: "das", meaning: "high school diploma", category: "school & education" },
    { word: "Amt", article: "das", meaning: "office / department", category: "city & places" },
    { word: "Alter", article: "das", meaning: "age", category: "family & people" },
    { word: "Klima", article: "das", meaning: "climate", category: "nature & weather" },
    { word: "Konsulat", article: "das", meaning: "consulate", category: "city & places" },
    { word: "Kraftfahrzeug", article: "das", meaning: "motor vehicle", category: "transportation" },
    { word: "Sparbuch", article: "das", meaning: "savings book", category: "shopping & money" },
    { word: "Verbot", article: "das", meaning: "ban / prohibition", category: "daily life & objects" },
    { word: "Vorbild", article: "das", meaning: "role model", category: "family & people" },
    { word: "Zelt", article: "das", meaning: "tent", category: "travel & vacation" },
    { word: "Zeugnis", article: "das", meaning: "report card", category: "school & education" },
    
    // ===== VERBS (Batch 1) =====
    { word: "ablehnen", meaning: "to reject", category: "verbs", type: "verb" },
    { word: "abnehmen", meaning: "to decrease / lose weight", category: "verbs", type: "verb" },
    { word: "abonnieren", meaning: "to subscribe", category: "verbs", type: "verb" },
    { word: "achten", meaning: "to pay attention", category: "verbs", type: "verb" },
    { word: "akzeptieren", meaning: "to accept", category: "verbs", type: "verb" },
    { word: "ändern", meaning: "to change", category: "verbs", type: "verb" },
    { word: "anerkennen", meaning: "to recognize / acknowledge", category: "verbs", type: "verb" },
    { word: "anmelden", meaning: "to register / log in", category: "verbs", type: "verb" },
    { word: "annehmen", meaning: "to accept / assume", category: "verbs", type: "verb" },
    { word: "ansehen", meaning: "to look at / watch", category: "verbs", type: "verb" },
    { word: "beantragen", meaning: "to apply for", category: "verbs", type: "verb" },
    { word: "bedienen", meaning: "to serve / operate", category: "verbs", type: "verb" },
    { word: "beeilen", meaning: "to hurry", category: "verbs", type: "verb" },
    { word: "behalten", meaning: "to keep", category: "verbs", type: "verb" },
    { word: "beleidigen", meaning: "to insult", category: "verbs", type: "verb" },
    { word: "beobachten", meaning: "to observe", category: "verbs", type: "verb" },
    { word: "beschäftigen", meaning: "to employ / occupy", category: "verbs", type: "verb" },
    { word: "beschließen", meaning: "to decide / conclude", category: "verbs", type: "verb" },
    { word: "bestätigen", meaning: "to confirm", category: "verbs", type: "verb" },
    { word: "bestehen", meaning: "to exist / pass (exam)", category: "verbs", type: "verb" },
    { word: "bewegen", meaning: "to move", category: "verbs", type: "verb" },
    { word: "beweisen", meaning: "to prove", category: "verbs", type: "verb" },
    { word: "bewerben", meaning: "to apply", category: "verbs", type: "verb" },
    { word: "bitten", meaning: "to ask / request", category: "verbs", type: "verb" },
    { word: "bleiben", meaning: "to stay", category: "verbs", type: "verb" },
    { word: "drehen", meaning: "to turn", category: "verbs", type: "verb" },
    { word: "drucken", meaning: "to print", category: "verbs", type: "verb" },
    { word: "drücken", meaning: "to press", category: "verbs", type: "verb" },
    { word: "einbauen", meaning: "to install", category: "verbs", type: "verb" },
    { word: "einbrechen", meaning: "to break in", category: "verbs", type: "verb" },
    { word: "einfallen", meaning: "to come to mind", category: "verbs", type: "verb" },
    { word: "einführen", meaning: "to introduce", category: "verbs", type: "verb" },
    { word: "einrichten", meaning: "to furnish", category: "verbs", type: "verb" },
    { word: "einsetzen", meaning: "to insert / deploy", category: "verbs", type: "verb" },
    { word: "einsteigen", meaning: "to board / get in", category: "verbs", type: "verb" },
    { word: "entdecken", meaning: "to discover", category: "verbs", type: "verb" },
    { word: "enthalten", meaning: "to contain", category: "verbs", type: "verb" },
    { word: "enttäuschen", meaning: "to disappoint", category: "verbs", type: "verb" },
    { word: "erfinden", meaning: "to invent", category: "verbs", type: "verb" },
    { word: "erfolgen", meaning: "to take place / happen", category: "verbs", type: "verb" },
    { word: "erhalten", meaning: "to receive", category: "verbs", type: "verb" },
    { word: "erholen", meaning: "to recover / relax", category: "verbs", type: "verb" },
    { word: "erlauben", meaning: "to allow", category: "verbs", type: "verb" },
    { word: "erledigen", meaning: "to get done / handle", category: "verbs", type: "verb" },
    { word: "erschrecken", meaning: "to frighten / be scared", category: "verbs", type: "verb" },
    { word: "fallengelassen", meaning: "to drop", category: "verbs", type: "verb" },
    { word: "fassen", meaning: "to grasp / hold", category: "verbs", type: "verb" },
    { word: "feiern", meaning: "to celebrate", category: "verbs", type: "verb" },
    { word: "fliehen", meaning: "to flee", category: "verbs", type: "verb" },
    { word: "fließen", meaning: "to flow", category: "verbs", type: "verb" },
    { word: "folgen", meaning: "to follow", category: "verbs", type: "verb" },
    { word: "fordern", meaning: "to demand", category: "verbs", type: "verb" },
    { word: "fürchten", meaning: "to fear", category: "verbs", type: "verb" },

    // ===== ADJECTIVES & ADVERBS (Batch 1) =====
    { word: "abhängig", meaning: "dependent", category: "adjectives", type: "adjective" },
    { word: "ähnlich", meaning: "similar", category: "adjectives", type: "adjective" },
    { word: "allgemein", meaning: "general", category: "adjectives", type: "adjective" },
    { word: "anwesend", meaning: "present", category: "adjectives", type: "adjective" },
    { word: "auffällig", meaning: "conspicuous", category: "adjectives", type: "adjective" },
    { word: "ausgezeichnet", meaning: "excellent", category: "adjectives", type: "adjective" },
    { word: "bedeutend", meaning: "significant", category: "adjectives", type: "adjective" },
    { word: "begeistert", meaning: "enthusiastic", category: "adjectives", type: "adjective" },
    { word: "bekannt", meaning: "known", category: "adjectives", type: "adjective" },
    { word: "beliebt", meaning: "popular", category: "adjectives", type: "adjective" },
    { word: "bereit", meaning: "ready", category: "adjectives", type: "adjective" },
    { word: "bestimmt", meaning: "certain / specific", category: "adjectives", type: "adjective" },
    { word: "deutlich", meaning: "clear / distinct", category: "adjectives", type: "adjective" },
    { word: "dicht", meaning: "dense / tight", category: "adjectives", type: "adjective" },
    { word: "dringend", meaning: "urgent", category: "adjectives", type: "adjective" },
    { word: "dünn", meaning: "thin", category: "adjectives", type: "adjective" },
    { word: "ehrlich", meaning: "honest", category: "adjectives", type: "adjective" },
    { word: "eindeutig", meaning: "unambiguous / clear", category: "adjectives", type: "adjective" },
    { word: "einzeln", meaning: "individual", category: "adjectives", type: "adjective" },
    { word: "eng", meaning: "narrow / tight", category: "adjectives", type: "adjective" },
    { word: "entfernt", meaning: "distant", category: "adjectives", type: "adjective" },
    { word: "entspannt", meaning: "relaxed", category: "adjectives", type: "adjective" },
    { word: "erfolglos", meaning: "unsuccessful", category: "adjectives", type: "adjective" },
    { word: "ernst", meaning: "serious", category: "adjectives", type: "adjective" },
    { word: "ewig", meaning: "eternal", category: "adjectives", type: "adjective" },
    { word: "fest", meaning: "firm / solid", category: "adjectives", type: "adjective" },
    { word: "flach", meaning: "flat", category: "adjectives", type: "adjective" },
    { word: "freiwillig", meaning: "voluntary", category: "adjectives", type: "adjective" },
    { word: "fremd", meaning: "foreign / strange", category: "adjectives", type: "adjective" },
    { word: "friedlich", meaning: "peaceful", category: "adjectives", type: "adjective" },
    { word: "allerdings", meaning: "however / certainly", category: "adverbs", type: "adverb" },
    { word: "anscheinend", meaning: "apparently", category: "adverbs", type: "adverb" },
    { word: "ausgerechnet", meaning: "of all things", category: "adverbs", type: "adverb" },
    { word: "außerdem", meaning: "besides / in addition", category: "adverbs", type: "adverb" },
    { word: "bereits", meaning: "already", category: "adverbs", type: "adverb" },
    { word: "bisher", meaning: "so far", category: "adverbs", type: "adverb" },
    { word: "dabei", meaning: "thereby / with it", category: "adverbs", type: "adverb" },
    { word: "dadurch", meaning: "through that / thereby", category: "adverbs", type: "adverb" },
    { word: "dafür", meaning: "for that", category: "adverbs", type: "adverb" },
    { word: "dagegen", meaning: "against it / on the other hand", category: "adverbs", type: "adverb" },
    { word: "damals", meaning: "back then", category: "adverbs", type: "adverb" },
    { word: "daneben", meaning: "next to it", category: "adverbs", type: "adverb" },
    { word: "daran", meaning: "on it / about it", category: "adverbs", type: "adverb" },
    { word: "darauf", meaning: "on it / afterwards", category: "adverbs", type: "adverb" },
    { word: "daraus", meaning: "from it", category: "adverbs", type: "adverb" },
    { word: "darin", meaning: "in it", category: "adverbs", type: "adverb" },
    { word: "darüber", meaning: "over it / about it", category: "adverbs", type: "adverb" },
    { word: "darum", meaning: "around it / therefore", category: "adverbs", type: "adverb" },
    { word: "darunter", meaning: "under it / among them", category: "adverbs", type: "adverb" },
    { word: "davon", meaning: "from it / of it", category: "adverbs", type: "adverb" },
    
    // ===== NOUNS (Batch 2) =====
    { word: "Affe", article: "der", meaning: "monkey", category: "animals" },
    { word: "Bär", article: "der", meaning: "bear", category: "animals" },
    { word: "Elefant", article: "der", meaning: "elephant", category: "animals" },
    { word: "Vogel", article: "der", meaning: "bird", category: "animals" },
    { word: "Wolf", article: "der", meaning: "wolf", category: "animals" },
    { word: "Bruder", article: "der", meaning: "brother", category: "family & people" },
    { word: "Onkel", article: "der", meaning: "uncle", category: "family & people" },
    { word: "Neffe", article: "der", meaning: "nephew", category: "family & people" },
    { word: "Schwiegervater", article: "der", meaning: "father-in-law", category: "family & people" },
    { word: "Enkel", article: "der", meaning: "grandson", category: "family & people" },
    { word: "Braten", article: "der", meaning: "roast (meat)", category: "food & drink" },
    { word: "Honig", article: "der", meaning: "honey", category: "food & drink" },
    { word: "Knoblauch", article: "der", meaning: "garlic", category: "food & drink" },
    { word: "Pfeffer", article: "der", meaning: "pepper (spice)", category: "food & drink" },
    { word: "Zucker", article: "der", meaning: "sugar", category: "food & drink" },
    { word: "Hals", article: "der", meaning: "neck / throat", category: "body & health" },
    { word: "Rücken", article: "der", meaning: "back", category: "body & health" },
    { word: "Zahn", article: "der", meaning: "tooth", category: "body & health" },
    { word: "Knochen", article: "der", meaning: "bone", category: "body & health" },
    { word: "Schmerz", article: "der", meaning: "pain", category: "body & health" },
    { word: "Mantel", article: "der", meaning: "coat", category: "clothing & accessories" },
    { word: "Rock", article: "der", meaning: "skirt", category: "clothing & accessories" },
    { word: "Schal", article: "der", meaning: "scarf", category: "clothing & accessories" },
    { word: "Handschuh", article: "der", meaning: "glove", category: "clothing & accessories" },
    { word: "Gürtel", article: "der", meaning: "belt", category: "clothing & accessories" },
    { word: "Flur", article: "der", meaning: "hallway", category: "house & furniture" },
    { word: "Teppich", article: "der", meaning: "carpet", category: "house & furniture" },
    { word: "Sessel", article: "der", meaning: "armchair", category: "house & furniture" },
    { word: "Schrank", article: "der", meaning: "cabinet / wardrobe", category: "house & furniture" },
    { word: "Herd", article: "der", meaning: "stove", category: "house & furniture" },
    { word: "Zug", article: "der", meaning: "train", category: "transportation" },
    { word: "Flug", article: "der", meaning: "flight", category: "transportation" },
    { word: "Führerschein", article: "der", meaning: "driver's license", category: "transportation" },
    { word: "Wagen", article: "der", meaning: "car / carriage", category: "transportation" },
    { word: "LKW", article: "der", meaning: "truck", category: "transportation" },
    { word: "Baum", article: "der", meaning: "tree", category: "nature & weather" },
    { word: "Berg", article: "der", meaning: "mountain", category: "nature & weather" },
    { word: "Fluss", article: "der", meaning: "river", category: "nature & weather" },
    { word: "Wald", article: "der", meaning: "forest", category: "nature & weather" },
    { word: "Stern", article: "der", meaning: "star", category: "nature & weather" },
    { word: "Maus", article: "die", meaning: "mouse", category: "animals" },
    { word: "Kuh", article: "die", meaning: "cow", category: "animals" },
    { word: "Spinne", article: "die", meaning: "spider", category: "animals" },
    { word: "Biene", article: "die", meaning: "bee", category: "animals" },
    { word: "Tante", article: "die", meaning: "aunt", category: "family & people" },
    { word: "Schwester", article: "die", meaning: "sister", category: "family & people" },
    { word: "Nichte", article: "die", meaning: "niece", category: "family & people" },
    { word: "Schwiegermutter", article: "die", meaning: "mother-in-law", category: "family & people" },
    { word: "Enkelin", article: "die", meaning: "granddaughter", category: "family & people" },
    { word: "Wurst", article: "die", meaning: "sausage", category: "food & drink" },
    { word: "Butter", article: "die", meaning: "butter", category: "food & drink" },
    { word: "Suppe", article: "die", meaning: "soup", category: "food & drink" },
    { word: "Zwiebel", article: "die", meaning: "onion", category: "food & drink" },
    { word: "Sahne", article: "die", meaning: "cream", category: "food & drink" },
    { word: "Nase", article: "die", meaning: "nose", category: "body & health" },
    { word: "Schulter", article: "die", meaning: "shoulder", category: "body & health" },
    { word: "Hand", article: "die", meaning: "hand", category: "body & health" },
    { word: "Wunde", article: "die", meaning: "wound", category: "body & health" },
    { word: "Apotheke", article: "die", meaning: "pharmacy", category: "body & health" },
    { word: "Hose", article: "die", meaning: "pants", category: "clothing & accessories" },
    { word: "Jacke", article: "die", meaning: "jacket", category: "clothing & accessories" },
    { word: "Tasche", article: "die", meaning: "bag", category: "clothing & accessories" },
    { word: "Socke", article: "die", meaning: "sock", category: "clothing & accessories" },
    { word: "Kette", article: "die", meaning: "necklace / chain", category: "clothing & accessories" },
    { word: "Wand", article: "die", meaning: "wall", category: "house & furniture" },
    { word: "Treppe", article: "die", meaning: "stairs", category: "house & furniture" },
    { word: "Tür", article: "die", meaning: "door", category: "house & furniture" },
    { word: "Lampe", article: "die", meaning: "lamp", category: "house & furniture" },
    { word: "Pflanze", article: "die", meaning: "plant", category: "house & furniture" },
    { word: "Bahn", article: "die", meaning: "train / railway", category: "transportation" },
    { word: "Straßenbahn", article: "die", meaning: "tram", category: "transportation" },
    { word: "Kreuzung", article: "die", meaning: "intersection", category: "transportation" },
    { word: "Haltestelle", article: "die", meaning: "stop / station", category: "transportation" },
    { word: "Tankstelle", article: "die", meaning: "gas station", category: "transportation" },
    { word: "Sonne", article: "die", meaning: "sun", category: "nature & weather" },
    { word: "Wolke", article: "die", meaning: "cloud", category: "nature & weather" },
    { word: "Blume", article: "die", meaning: "flower", category: "nature & weather" },
    { word: "Pferd", article: "das", meaning: "horse", category: "animals" },
    { word: "Schwein", article: "das", meaning: "pig", category: "animals" },
    { word: "Schaf", article: "das", meaning: "sheep", category: "animals" },
    { word: "Insekt", article: "das", meaning: "insect", category: "animals" },
    { word: "Geschwister", article: "das", meaning: "sibling(s)", category: "family & people" },
    { word: "Baby", article: "das", meaning: "baby", category: "family & people" },
    { word: "Mädchen", article: "das", meaning: "girl", category: "family & people" },
    { word: "Fleisch", article: "das", meaning: "meat", category: "food & drink" },
    { word: "Gemüse", article: "das", meaning: "vegetables", category: "food & drink" },
    { word: "Salz", article: "das", meaning: "salt", category: "food & drink" },
    { word: "Mehl", article: "das", meaning: "flour", category: "food & drink" },
    { word: "Auge", article: "das", meaning: "eye", category: "body & health" },
    { word: "Ohr", article: "das", meaning: "ear", category: "body & health" },
    { word: "Bein", article: "das", meaning: "leg", category: "body & health" },
    { word: "Blut", article: "das", meaning: "blood", category: "body & health" },
    { word: "Herz", article: "das", meaning: "heart", category: "body & health" },
    { word: "Kleid", article: "das", meaning: "dress", category: "clothing & accessories" },
    { word: "Hemd", article: "das", meaning: "shirt", category: "clothing & accessories" },
    { word: "T-Shirt", article: "das", meaning: "t-shirt", category: "clothing & accessories" },
    { word: "Dach", article: "das", meaning: "roof", category: "house & furniture" },
    { word: "Fenster", article: "das", meaning: "window", category: "house & furniture" },
    { word: "Bad", article: "das", meaning: "bathroom", category: "house & furniture" },
    { word: "Schlafzimmer", article: "das", meaning: "bedroom", category: "house & furniture" },
    { word: "Fahrrad", article: "das", meaning: "bicycle", category: "transportation" },
    { word: "Schiff", article: "das", meaning: "ship", category: "transportation" },
    { word: "Flugzeug", article: "das", meaning: "airplane", category: "transportation" },
    { word: "Auto", article: "das", meaning: "car", category: "transportation" },
    { word: "Taxi", article: "das", meaning: "taxi", category: "transportation" },
    { word: "Meer", article: "das", meaning: "sea / ocean", category: "nature & weather" },
    { word: "Wetter", article: "das", meaning: "weather", category: "nature & weather" },

    // ===== VERBS (Batch 2) =====
    { word: "fühlen", meaning: "to feel", category: "verbs", type: "verb" },
    { word: "führen", meaning: "to lead / guide", category: "verbs", type: "verb" },
    { word: "frieren", meaning: "to freeze / be cold", category: "verbs", type: "verb" },
    { word: "genügen", meaning: "to suffice / be enough", category: "verbs", type: "verb" },
    { word: "geraten", meaning: "to get into", category: "verbs", type: "verb" },
    { word: "geschehen", meaning: "to happen", category: "verbs", type: "verb" },
    { word: "gewöhnen", meaning: "to get used to", category: "verbs", type: "verb" },
    { word: "greifen", meaning: "to grab / catch", category: "verbs", type: "verb" },
    { word: "grüßen", meaning: "to greet", category: "verbs", type: "verb" },
    { word: "halten", meaning: "to hold / stop", category: "verbs", type: "verb" },
    { word: "handeln", meaning: "to act / trade", category: "verbs", type: "verb" },
    { word: "hoffen", meaning: "to hope", category: "verbs", type: "verb" },
    { word: "informieren", meaning: "to inform", category: "verbs", type: "verb" },
    { word: "irren", meaning: "to err / be wrong", category: "verbs", type: "verb" },
    { word: "kämpfen", meaning: "to fight", category: "verbs", type: "verb" },
    { word: "kennenlernen", meaning: "to get to know", category: "verbs", type: "verb" },
    { word: "klappen", meaning: "to work out / fold", category: "verbs", type: "verb" },
    { word: "klingen", meaning: "to sound", category: "verbs", type: "verb" },
    { word: "klären", meaning: "to clarify", category: "verbs", type: "verb" },
    { word: "laden", meaning: "to load", category: "verbs", type: "verb" },
    { word: "lassen", meaning: "to let / leave", category: "verbs", type: "verb" },
    { word: "leiden", meaning: "to suffer", category: "verbs", type: "verb" },
    { word: "leihen", meaning: "to lend / borrow", category: "verbs", type: "verb" },
    { word: "leisten", meaning: "to afford / achieve", category: "verbs", type: "verb" },
    { word: "leiten", meaning: "to lead / direct", category: "verbs", type: "verb" },
    { word: "liefern", meaning: "to deliver", category: "verbs", type: "verb" },
    { word: "lohnen", meaning: "to be worth it", category: "verbs", type: "verb" },
    { word: "lügen", meaning: "to lie", category: "verbs", type: "verb" },
    { word: "melden", meaning: "to report", category: "verbs", type: "verb" },
    { word: "merken", meaning: "to notice / remember", category: "verbs", type: "verb" },
    { word: "messen", meaning: "to measure", category: "verbs", type: "verb" },
    { word: "mitteilen", meaning: "to inform", category: "verbs", type: "verb" },
    { word: "nachdenken", meaning: "to think about", category: "verbs", type: "verb" },
    { word: "nennen", meaning: "to name / call", category: "verbs", type: "verb" },
    { word: "nutzen", meaning: "to use", category: "verbs", type: "verb" },
    { word: "passen", meaning: "to fit", category: "verbs", type: "verb" },
    { word: "pflegen", meaning: "to care for", category: "verbs", type: "verb" },
    { word: "prüfen", meaning: "to check / examine", category: "verbs", type: "verb" },
    { word: "raten", meaning: "to advise / guess", category: "verbs", type: "verb" },
    { word: "reagieren", meaning: "to react", category: "verbs", type: "verb" },
    { word: "rechnen", meaning: "to calculate", category: "verbs", type: "verb" },
    { word: "reden", meaning: "to talk", category: "verbs", type: "verb" },
    { word: "reichen", meaning: "to be enough / hand", category: "verbs", type: "verb" },
    { word: "reiten", meaning: "to ride (horse)", category: "verbs", type: "verb" },
    { word: "rennen", meaning: "to run", category: "verbs", type: "verb" },
    { word: "retten", meaning: "to save / rescue", category: "verbs", type: "verb" },
    { word: "riechen", meaning: "to smell", category: "verbs", type: "verb" },
    { word: "rufen", meaning: "to call", category: "verbs", type: "verb" },
    { word: "ruhen", meaning: "to rest", category: "verbs", type: "verb" },
    { word: "sammeln", meaning: "to collect", category: "verbs", type: "verb" },

    // ===== ADJECTIVES & ADVERBS (Batch 2) =====
    { word: "frisch", meaning: "fresh", category: "adjectives", type: "adjective" },
    { word: "froh", meaning: "glad", category: "adjectives", type: "adjective" },
    { word: "früh", meaning: "early", category: "adjectives", type: "adjective" },
    { word: "furchtbar", meaning: "terrible", category: "adjectives", type: "adjective" },
    { word: "geduldig", meaning: "patient", category: "adjectives", type: "adjective" },
    { word: "geheim", meaning: "secret", category: "adjectives", type: "adjective" },
    { word: "gemeinsam", meaning: "together / common", category: "adjectives", type: "adjective" },
    { word: "genau", meaning: "exact", category: "adjectives", type: "adjective" },
    { word: "gerade", meaning: "straight", category: "adjectives", type: "adjective" },
    { word: "gerecht", meaning: "fair / just", category: "adjectives", type: "adjective" },
    { word: "gesund", meaning: "healthy", category: "adjectives", type: "adjective" },
    { word: "gewöhnlich", meaning: "usual / ordinary", category: "adjectives", type: "adjective" },
    { word: "glatt", meaning: "smooth / slippery", category: "adjectives", type: "adjective" },
    { word: "gleich", meaning: "equal / same", category: "adjectives", type: "adjective" },
    { word: "gültig", meaning: "valid", category: "adjectives", type: "adjective" },
    { word: "hart", meaning: "hard", category: "adjectives", type: "adjective" },
    { word: "hässlich", meaning: "ugly", category: "adjectives", type: "adjective" },
    { word: "häufig", meaning: "frequent", category: "adjectives", type: "adjective" },
    { word: "heimlich", meaning: "secretly", category: "adjectives", type: "adjective" },
    { word: "hell", meaning: "bright / light", category: "adjectives", type: "adjective" },
    { word: "herrlich", meaning: "wonderful", category: "adjectives", type: "adjective" },
    { word: "höflich", meaning: "polite", category: "adjectives", type: "adjective" },
    { word: "hübsch", meaning: "pretty", category: "adjectives", type: "adjective" },
    { word: "hungrig", meaning: "hungry", category: "adjectives", type: "adjective" },
    { word: "innerlich", meaning: "internal", category: "adjectives", type: "adjective" },
    { word: "kalt", meaning: "cold", category: "adjectives", type: "adjective" },
    { word: "kaputt", meaning: "broken", category: "adjectives", type: "adjective" },
    { word: "klar", meaning: "clear", category: "adjectives", type: "adjective" },
    { word: "klug", meaning: "smart", category: "adjectives", type: "adjective" },
    { word: "komisch", meaning: "funny / weird", category: "adjectives", type: "adjective" },
    { word: "dazu", meaning: "in addition / to it", category: "adverbs", type: "adverb" },
    { word: "demnach", meaning: "accordingly", category: "adverbs", type: "adverb" },
    { word: "dennoch", meaning: "nevertheless", category: "adverbs", type: "adverb" },
    { word: "direkt", meaning: "directly", category: "adverbs", type: "adverb" },
    { word: "dort", meaning: "there", category: "adverbs", type: "adverb" },
    { word: "drüben", meaning: "over there", category: "adverbs", type: "adverb" },
    { word: "durchaus", meaning: "absolutely", category: "adverbs", type: "adverb" },
    { word: "eben", meaning: "just / even", category: "adverbs", type: "adverb" },
    { word: "ebenfalls", meaning: "also", category: "adverbs", type: "adverb" },
    { word: "ebenso", meaning: "just as / equally", category: "adverbs", type: "adverb" },
    { word: "eher", meaning: "rather / sooner", category: "adverbs", type: "adverb" },
    { word: "einigermaßen", meaning: "somewhat", category: "adverbs", type: "adverb" },
    { word: "einmal", meaning: "once", category: "adverbs", type: "adverb" },
    { word: "endlich", meaning: "finally", category: "adverbs", type: "adverb" },
    { word: "entgegen", meaning: "contrary to", category: "adverbs", type: "adverb" },
    { word: "erst", meaning: "only / first", category: "adverbs", type: "adverb" },
    { word: "etwa", meaning: "about / approximately", category: "adverbs", type: "adverb" },
    { word: "fast", meaning: "almost", category: "adverbs", type: "adverb" },
    { word: "folglich", meaning: "consequently", category: "adverbs", type: "adverb" },
    { word: "fort", meaning: "away", category: "adverbs", type: "adverb" },

    // ===== PREPOSITIONS & CONJUNCTIONS (Batch 3) =====
    { word: "ab", meaning: "from (time/place)", category: "prepositions", type: "preposition" },
    { word: "gegen", meaning: "against / around (time)", category: "prepositions", type: "preposition" },
    { word: "ohne", meaning: "without", category: "prepositions", type: "preposition" },
    { word: "seit", meaning: "since / for (time)", category: "prepositions", type: "preposition" },
    { word: "um", meaning: "around / at (time)", category: "prepositions", type: "preposition" },
    { word: "bis", meaning: "until / up to", category: "prepositions", type: "preposition" },
    { word: "durch", meaning: "through", category: "prepositions", type: "preposition" },
    { word: "entlang", meaning: "along", category: "prepositions", type: "preposition" },
    { word: "inklusive", meaning: "including", category: "prepositions", type: "preposition" },
    { word: "außer", meaning: "except for", category: "prepositions", type: "preposition" },
    { word: "dass", meaning: "that", category: "conjunctions", type: "conjunction" },
    { word: "ob", meaning: "whether / if", category: "conjunctions", type: "conjunction" },
    { word: "weil", meaning: "because", category: "conjunctions", type: "conjunction" },
    { word: "obwohl", meaning: "although", category: "conjunctions", type: "conjunction" },
    { word: "da", meaning: "since / because", category: "conjunctions", type: "conjunction" },
    { word: "damit", meaning: "so that", category: "conjunctions", type: "conjunction" },
    { word: "falls", meaning: "in case / if", category: "conjunctions", type: "conjunction" },
    { word: "nachdem", meaning: "after", category: "conjunctions", type: "conjunction" },
    { word: "bevor", meaning: "before", category: "conjunctions", type: "conjunction" },
    { word: "während", meaning: "while / during", category: "conjunctions", type: "conjunction" },

    // ===== MORE NOUNS (Batch 3) =====
    { word: "Brief", article: "der", meaning: "letter", category: "communication & media" },
    { word: "Schlüssel", article: "der", meaning: "key", category: "daily life & objects" },
    { word: "Boden", article: "der", meaning: "floor / ground", category: "house & furniture" },
    { word: "Stift", article: "der", meaning: "pen", category: "school & education" },
    { word: "Zettel", article: "der", meaning: "note / slip of paper", category: "school & education" },
    { word: "Abend", article: "der", meaning: "evening", category: "time & calendar" },
    { word: "Feierabend", article: "der", meaning: "quitting time / end of workday", category: "time & calendar" },
    { word: "Monat", article: "der", meaning: "month", category: "time & calendar" },
    { word: "Moment", article: "der", meaning: "moment", category: "time & calendar" },
    { word: "Platz", article: "der", meaning: "square / place / seat", category: "city & places" },
    { word: "Markt", article: "der", meaning: "market", category: "city & places" },
    { word: "Park", article: "der", meaning: "park", category: "city & places" },
    { word: "See", article: "der", meaning: "lake", category: "nature & weather" },
    { word: "Strand", article: "der", meaning: "beach", category: "nature & weather" },
    { word: "Urlaub", article: "der", meaning: "vacation", category: "travel & vacation" },
    { word: "Ausflug", article: "der", meaning: "excursion / trip", category: "travel & vacation" },
    { word: "Beruf", article: "der", meaning: "profession / job", category: "work & profession" },
    { word: "Chef", article: "der", meaning: "boss", category: "work & profession" },
    { word: "Kollege", article: "der", meaning: "colleague", category: "work & profession" },
    { word: "Gast", article: "der", meaning: "guest", category: "family & people" },
    { word: "Mensch", article: "der", meaning: "human / person", category: "family & people" },
    { word: "Kopf", article: "der", meaning: "head", category: "body & health" },
    { word: "Magen", article: "der", meaning: "stomach", category: "body & health" },
    { word: "Arm", article: "der", meaning: "arm", category: "body & health" },
    { word: "Fuß", article: "der", meaning: "foot", category: "body & health" },
    { word: "Finger", article: "der", meaning: "finger", category: "body & health" },
    { word: "Bauch", article: "der", meaning: "belly / stomach", category: "body & health" },
    { word: "Durst", article: "der", meaning: "thirst", category: "food & drink" },
    { word: "Hunger", article: "der", meaning: "hunger", category: "food & drink" },
    { word: "Appetit", article: "der", meaning: "appetite", category: "food & drink" },
    { word: "Kaffee", article: "der", meaning: "coffee", category: "food & drink" },
    { word: "Tee", article: "der", meaning: "tea", category: "food & drink" },
    { word: "Saft", article: "der", meaning: "juice", category: "food & drink" },
    { word: "Wein", article: "der", meaning: "wine", category: "food & drink" },
    { word: "Reis", article: "der", meaning: "rice", category: "food & drink" },
    { word: "Käse", article: "der", meaning: "cheese", category: "food & drink" },
    { word: "Apfel", article: "der", meaning: "apple", category: "food & drink" },
    { word: "Kuchen", article: "der", meaning: "cake", category: "food & drink" },
    { word: "Salat", article: "der", meaning: "salad", category: "food & drink" },
    { word: "Fisch", article: "der", meaning: "fish", category: "food & drink" },
    { word: "Umschlag", article: "der", meaning: "envelope", category: "communication & media" },
    { word: "Briefmarke", article: "die", meaning: "postage stamp", category: "communication & media" },
    { word: "Post", article: "die", meaning: "post office / mail", category: "communication & media" },
    { word: "Adresse", article: "die", meaning: "address", category: "communication & media" },
    { word: "Nachricht", article: "die", meaning: "message / news", category: "communication & media" },
    { word: "Information", article: "die", meaning: "information", category: "communication & media" },
    { word: "Zeitung", article: "die", meaning: "newspaper", category: "communication & media" },
    { word: "Rechnung", article: "die", meaning: "bill / invoice", category: "shopping & money" },
    { word: "Tüte", article: "die", meaning: "bag (plastic or paper)", category: "shopping & money" },
    { word: "Kreditkarte", article: "die", meaning: "credit card", category: "shopping & money" },
    { word: "Münze", article: "die", meaning: "coin", category: "shopping & money" },
    { word: "Bank", article: "die", meaning: "bank / bench", category: "shopping & money" },
    { word: "Firma", article: "die", meaning: "company", category: "work & profession" },
    { word: "Arbeit", article: "die", meaning: "work", category: "work & profession" },
    { word: "Pause", article: "die", meaning: "break / pause", category: "work & profession" },
    { word: "Stelle", article: "die", meaning: "job / position / place", category: "work & profession" },
    { word: "Schule", article: "die", meaning: "school", category: "school & education" },
    { word: "Klasse", article: "die", meaning: "class", category: "school & education" },
    { word: "Aufgabe", article: "die", meaning: "task / assignment", category: "school & education" },
    { word: "Idee", article: "die", meaning: "idea", category: "school & education" },
    { word: "Antwort", article: "die", meaning: "answer", category: "school & education" },
    { word: "Frage", article: "die", meaning: "question", category: "school & education" },
    { word: "Sprache", article: "die", meaning: "language", category: "school & education" },
    { word: "Uhr", article: "die", meaning: "clock / watch / o'clock", category: "time & calendar" },
    { word: "Zeit", article: "die", meaning: "time", category: "time & calendar" },
    { word: "Woche", article: "die", meaning: "week", category: "time & calendar" },
    { word: "Nacht", article: "die", meaning: "night", category: "time & calendar" },
    { word: "Reise", article: "die", meaning: "journey / trip", category: "travel & vacation" },
    { word: "Fahrkarte", article: "die", meaning: "ticket", category: "transportation" },
    { word: "U-Bahn", article: "die", meaning: "subway", category: "transportation" },
    { word: "Straße", article: "die", meaning: "street", category: "city & places" },
    { word: "Stadt", article: "die", meaning: "city", category: "city & places" },
    { word: "Wohnung", article: "die", meaning: "apartment", category: "house & furniture" },
    { word: "Küche", article: "die", meaning: "kitchen", category: "house & furniture" },
    { word: "Dusche", article: "die", meaning: "shower", category: "house & furniture" },
    { word: "Möbel", article: "die", meaning: "furniture", category: "house & furniture" },
    { word: "Brille", article: "die", meaning: "glasses", category: "clothing & accessories" },
    { word: "Milch", article: "die", meaning: "milk", category: "food & drink" },
    { word: "Marmelade", article: "die", meaning: "jam", category: "food & drink" },
    { word: "Schokolade", article: "die", meaning: "chocolate", category: "food & drink" },
    { word: "Kartoffel", article: "die", meaning: "potato", category: "food & drink" },
    { word: "Tomate", article: "die", meaning: "tomato", category: "food & drink" },
    { word: "Flasche", article: "die", meaning: "bottle", category: "food & drink" },
    { word: "Tasse", article: "die", meaning: "cup", category: "food & drink" },
    { word: "Gabel", article: "die", meaning: "fork", category: "food & drink" },
    { word: "Mutter", article: "die", meaning: "mother", category: "family & people" },
    { word: "Frau", article: "die", meaning: "woman / wife / Mrs.", category: "family & people" },
    { word: "Person", article: "die", meaning: "person", category: "family & people" },
    { word: "Büro", article: "das", meaning: "office", category: "work & profession" },
    { word: "Hotel", article: "das", meaning: "hotel", category: "travel & vacation" },
    { word: "Restaurant", article: "das", meaning: "restaurant", category: "city & places" },
    { word: "Café", article: "das", meaning: "cafe", category: "city & places" },
    { word: "Geschäft", article: "das", meaning: "shop / business", category: "shopping & money" },
    { word: "Zimmer", article: "das", meaning: "room", category: "house & furniture" },
    { word: "Bett", article: "das", meaning: "bed", category: "house & furniture" },
    { word: "Sofa", article: "das", meaning: "sofa", category: "house & furniture" },
    { word: "Regal", article: "das", meaning: "shelf", category: "house & furniture" },
    { word: "Buch", article: "das", meaning: "book", category: "school & education" },
    { word: "Heft", article: "das", meaning: "notebook", category: "school & education" },
    { word: "Wort", article: "das", meaning: "word", category: "school & education" },
    { word: "Bild", article: "das", meaning: "picture / image", category: "daily life & objects" },
    { word: "Foto", article: "das", meaning: "photo", category: "daily life & objects" },
    { word: "Papier", article: "das", meaning: "paper", category: "daily life & objects" },
    { word: "Internet", article: "das", meaning: "internet", category: "communication & media" },
    { word: "Telefon", article: "das", meaning: "phone", category: "communication & media" },
    { word: "Radio", article: "das", meaning: "radio", category: "communication & media" },
    { word: "Geld", article: "das", meaning: "money", category: "shopping & money" },
    { word: "Ticket", article: "das", meaning: "ticket", category: "transportation" },
    { word: "Kino", article: "das", meaning: "cinema", category: "city & places" },
    { word: "Museum", article: "das", meaning: "museum", category: "city & places" },
    { word: "Theater", article: "das", meaning: "theater", category: "city & places" },
    { word: "Krankenhaus", article: "das", meaning: "hospital", category: "city & places" },
    { word: "Dorf", article: "das", meaning: "village", category: "city & places" },
    { word: "Land", article: "das", meaning: "country / land", category: "city & places" },
    { word: "Problem", article: "das", meaning: "problem", category: "daily life & objects" },
    { word: "Jahr", article: "das", meaning: "year", category: "time & calendar" },
    { word: "Wochenende", article: "das", meaning: "weekend", category: "time & calendar" },
    { word: "Leben", article: "das", meaning: "life", category: "daily life & objects" },
    { word: "Brot", article: "das", meaning: "bread", category: "food & drink" },
    { word: "Brötchen", article: "das", meaning: "bread roll", category: "food & drink" },
    { word: "Wasser", article: "das", meaning: "water", category: "food & drink" },
    { word: "Bier", article: "das", meaning: "beer", category: "food & drink" },
    { word: "Ei", article: "das", meaning: "egg", category: "food & drink" },
    { word: "Obst", article: "das", meaning: "fruit", category: "food & drink" },
    { word: "Glas", article: "das", meaning: "glass", category: "food & drink" },
    { word: "Messer", article: "das", meaning: "knife", category: "food & drink" },
    { word: "Frühstück", article: "das", meaning: "breakfast", category: "food & drink" },
    { word: "Abendessen", article: "das", meaning: "dinner", category: "food & drink" },
    { word: "Gesicht", article: "das", meaning: "face", category: "body & health" },
    { word: "Haar", article: "das", meaning: "hair", category: "body & health" },
    { word: "Fieber", article: "das", meaning: "fever", category: "body & health" },
    { word: "Pflaster", article: "das", meaning: "band-aid / plaster", category: "body & health" },
    { word: "Rezept", article: "das", meaning: "recipe / prescription", category: "body & health" },
    { word: "Haustier", article: "das", meaning: "pet", category: "animals" },
    { word: "Spiel", article: "das", meaning: "game", category: "hobbies & sports" },
    { word: "Hobby", article: "das", meaning: "hobby", category: "hobbies & sports" }
];
