const A1_WORDS = [
    // ===== ANIMALS =====
    { word: "Hund", article: "der", meaning: "dog", category: "animals" },
    { word: "Katze", article: "die", meaning: "cat", category: "animals" },
    { word: "Vogel", article: "der", meaning: "bird", category: "animals" },
    { word: "Fisch", article: "der", meaning: "fish", category: "animals" },
    { word: "Pferd", article: "das", meaning: "horse", category: "animals" },
    { word: "Kuh", article: "die", meaning: "cow", category: "animals" },
    { word: "Schwein", article: "das", meaning: "pig", category: "animals" },
    { word: "Maus", article: "die", meaning: "mouse", category: "animals" },
    { word: "Bär", article: "der", meaning: "bear", category: "animals" },
    { word: "Hase", article: "der", meaning: "rabbit", category: "animals" },
    { word: "Schaf", article: "das", meaning: "sheep", category: "animals" },
    { word: "Huhn", article: "das", meaning: "chicken", category: "animals" },
    { word: "Ente", article: "die", meaning: "duck", category: "animals" },
    { word: "Elefant", article: "der", meaning: "elephant", category: "animals" },
    { word: "Affe", article: "der", meaning: "monkey", category: "animals" },
    { word: "Schlange", article: "die", meaning: "snake", category: "animals" },
    { word: "Löwe", article: "der", meaning: "lion", category: "animals" },
    { word: "Tiger", article: "der", meaning: "tiger", category: "animals" },
    { word: "Schmetterling", article: "der", meaning: "butterfly", category: "animals" },
    { word: "Tier", article: "das", meaning: "animal", category: "animals" },
    { word: "Ziege", article: "die", meaning: "goat", category: "animals" },
    { word: "Frosch", article: "der", meaning: "frog", category: "animals" },
    { word: "Spinne", article: "die", meaning: "spider", category: "animals" },
    { word: "Insekt", article: "das", meaning: "insect", category: "animals" },
    { word: "Wolf", article: "der", meaning: "wolf", category: "animals" },

    // ===== FOOD & DRINK =====
    { word: "Brot", article: "das", meaning: "bread", category: "food & drink" },
    { word: "Wasser", article: "das", meaning: "water", category: "food & drink" },
    { word: "Milch", article: "die", meaning: "milk", category: "food & drink" },
    { word: "Kaffee", article: "der", meaning: "coffee", category: "food & drink" },
    { word: "Tee", article: "der", meaning: "tea", category: "food & drink" },
    { word: "Saft", article: "der", meaning: "juice", category: "food & drink" },
    { word: "Bier", article: "das", meaning: "beer", category: "food & drink" },
    { word: "Wein", article: "der", meaning: "wine", category: "food & drink" },
    { word: "Apfel", article: "der", meaning: "apple", category: "food & drink" },
    { word: "Banane", article: "die", meaning: "banana", category: "food & drink" },
    { word: "Orange", article: "die", meaning: "orange", category: "food & drink" },
    { word: "Tomate", article: "die", meaning: "tomato", category: "food & drink" },
    { word: "Kartoffel", article: "die", meaning: "potato", category: "food & drink" },
    { word: "Reis", article: "der", meaning: "rice", category: "food & drink" },
    { word: "Nudel", article: "die", meaning: "noodle", category: "food & drink" },
    { word: "Fleisch", article: "das", meaning: "meat", category: "food & drink" },
    { word: "Käse", article: "der", meaning: "cheese", category: "food & drink" },
    { word: "Butter", article: "die", meaning: "butter", category: "food & drink" },
    { word: "Ei", article: "das", meaning: "egg", category: "food & drink" },
    { word: "Zucker", article: "der", meaning: "sugar", category: "food & drink" },
    { word: "Salz", article: "das", meaning: "salt", category: "food & drink" },
    { word: "Suppe", article: "die", meaning: "soup", category: "food & drink" },
    { word: "Salat", article: "der", meaning: "salad", category: "food & drink" },
    { word: "Kuchen", article: "der", meaning: "cake", category: "food & drink" },
    { word: "Schokolade", article: "die", meaning: "chocolate", category: "food & drink" },
    { word: "Essen", article: "das", meaning: "food", category: "food & drink" },
    { word: "Getränk", article: "das", meaning: "drink", category: "food & drink" },
    { word: "Obst", article: "das", meaning: "fruit", category: "food & drink" },
    { word: "Gemüse", article: "das", meaning: "vegetables", category: "food & drink" },
    { word: "Hähnchen", article: "das", meaning: "chicken (meat)", category: "food & drink" },
    { word: "Erdbeere", article: "die", meaning: "strawberry", category: "food & drink" },

    // ===== FAMILY & PEOPLE =====
    { word: "Mutter", article: "die", meaning: "mother", category: "family & people" },
    { word: "Vater", article: "der", meaning: "father", category: "family & people" },
    { word: "Kind", article: "das", meaning: "child", category: "family & people" },
    { word: "Bruder", article: "der", meaning: "brother", category: "family & people" },
    { word: "Schwester", article: "die", meaning: "sister", category: "family & people" },
    { word: "Sohn", article: "der", meaning: "son", category: "family & people" },
    { word: "Tochter", article: "die", meaning: "daughter", category: "family & people" },
    { word: "Großmutter", article: "die", meaning: "grandmother", category: "family & people" },
    { word: "Großvater", article: "der", meaning: "grandfather", category: "family & people" },
    { word: "Onkel", article: "der", meaning: "uncle", category: "family & people" },
    { word: "Tante", article: "die", meaning: "aunt", category: "family & people" },
    { word: "Mann", article: "der", meaning: "man", category: "family & people" },
    { word: "Frau", article: "die", meaning: "woman", category: "family & people" },
    { word: "Mädchen", article: "das", meaning: "girl", category: "family & people" },
    { word: "Junge", article: "der", meaning: "boy", category: "family & people" },
    { word: "Baby", article: "das", meaning: "baby", category: "family & people" },
    { word: "Freund", article: "der", meaning: "friend (male)", category: "family & people" },
    { word: "Freundin", article: "die", meaning: "friend (female)", category: "family & people" },
    { word: "Familie", article: "die", meaning: "family", category: "family & people" },
    { word: "Eltern", article: "die", meaning: "parents", category: "family & people" },
    { word: "Nachbar", article: "der", meaning: "neighbor", category: "family & people" },
    { word: "Mensch", article: "der", meaning: "person", category: "family & people" },
    { word: "Leute", article: "die", meaning: "people", category: "family & people" },
    { word: "Cousin", article: "der", meaning: "cousin (male)", category: "family & people" },
    { word: "Cousine", article: "die", meaning: "cousin (female)", category: "family & people" },

    // ===== BODY & HEALTH =====
    { word: "Kopf", article: "der", meaning: "head", category: "body & health" },
    { word: "Auge", article: "das", meaning: "eye", category: "body & health" },
    { word: "Ohr", article: "das", meaning: "ear", category: "body & health" },
    { word: "Nase", article: "die", meaning: "nose", category: "body & health" },
    { word: "Mund", article: "der", meaning: "mouth", category: "body & health" },
    { word: "Zahn", article: "der", meaning: "tooth", category: "body & health" },
    { word: "Hand", article: "die", meaning: "hand", category: "body & health" },
    { word: "Fuß", article: "der", meaning: "foot", category: "body & health" },
    { word: "Arm", article: "der", meaning: "arm", category: "body & health" },
    { word: "Bein", article: "das", meaning: "leg", category: "body & health" },
    { word: "Finger", article: "der", meaning: "finger", category: "body & health" },
    { word: "Haar", article: "das", meaning: "hair", category: "body & health" },
    { word: "Herz", article: "das", meaning: "heart", category: "body & health" },
    { word: "Rücken", article: "der", meaning: "back", category: "body & health" },
    { word: "Bauch", article: "der", meaning: "stomach", category: "body & health" },
    { word: "Gesicht", article: "das", meaning: "face", category: "body & health" },
    { word: "Hals", article: "der", meaning: "neck", category: "body & health" },
    { word: "Arzt", article: "der", meaning: "doctor", category: "body & health" },
    { word: "Ärztin", article: "die", meaning: "doctor (female)", category: "body & health" },
    { word: "Krankenhaus", article: "das", meaning: "hospital", category: "body & health" },
    { word: "Medizin", article: "die", meaning: "medicine", category: "body & health" },
    { word: "Schmerz", article: "der", meaning: "pain", category: "body & health" },
    { word: "Körper", article: "der", meaning: "body", category: "body & health" },
    { word: "Apotheke", article: "die", meaning: "pharmacy", category: "body & health" },
    { word: "Gesundheit", article: "die", meaning: "health", category: "body & health" },

    // ===== CLOTHING & ACCESSORIES =====
    { word: "Hose", article: "die", meaning: "pants", category: "clothing & accessories" },
    { word: "Hemd", article: "das", meaning: "shirt", category: "clothing & accessories" },
    { word: "Kleid", article: "das", meaning: "dress", category: "clothing & accessories" },
    { word: "Rock", article: "der", meaning: "skirt", category: "clothing & accessories" },
    { word: "Jacke", article: "die", meaning: "jacket", category: "clothing & accessories" },
    { word: "Mantel", article: "der", meaning: "coat", category: "clothing & accessories" },
    { word: "Schuh", article: "der", meaning: "shoe", category: "clothing & accessories" },
    { word: "Stiefel", article: "der", meaning: "boot", category: "clothing & accessories" },
    { word: "Hut", article: "der", meaning: "hat", category: "clothing & accessories" },
    { word: "Mütze", article: "die", meaning: "cap", category: "clothing & accessories" },
    { word: "Handschuh", article: "der", meaning: "glove", category: "clothing & accessories" },
    { word: "Schal", article: "der", meaning: "scarf", category: "clothing & accessories" },
    { word: "Brille", article: "die", meaning: "glasses", category: "clothing & accessories" },
    { word: "Tasche", article: "die", meaning: "bag", category: "clothing & accessories" },
    { word: "Gürtel", article: "der", meaning: "belt", category: "clothing & accessories" },
    { word: "Socke", article: "die", meaning: "sock", category: "clothing & accessories" },
    { word: "Pullover", article: "der", meaning: "sweater", category: "clothing & accessories" },
    { word: "Anzug", article: "der", meaning: "suit", category: "clothing & accessories" },
    { word: "Bluse", article: "die", meaning: "blouse", category: "clothing & accessories" },
    { word: "Ring", article: "der", meaning: "ring", category: "clothing & accessories" },
    { word: "Uhr", article: "die", meaning: "watch", category: "clothing & accessories" },
    { word: "Kette", article: "die", meaning: "necklace", category: "clothing & accessories" },
    { word: "Regenschirm", article: "der", meaning: "umbrella", category: "clothing & accessories" },
    { word: "Kleidung", article: "die", meaning: "clothing", category: "clothing & accessories" },
    { word: "Jeans", article: "die", meaning: "jeans", category: "clothing & accessories" },

    // ===== HOUSE & FURNITURE =====
    { word: "Haus", article: "das", meaning: "house", category: "house & furniture" },
    { word: "Wohnung", article: "die", meaning: "apartment", category: "house & furniture" },
    { word: "Zimmer", article: "das", meaning: "room", category: "house & furniture" },
    { word: "Küche", article: "die", meaning: "kitchen", category: "house & furniture" },
    { word: "Bad", article: "das", meaning: "bathroom", category: "house & furniture" },
    { word: "Schlafzimmer", article: "das", meaning: "bedroom", category: "house & furniture" },
    { word: "Wohnzimmer", article: "das", meaning: "living room", category: "house & furniture" },
    { word: "Tür", article: "die", meaning: "door", category: "house & furniture" },
    { word: "Fenster", article: "das", meaning: "window", category: "house & furniture" },
    { word: "Tisch", article: "der", meaning: "table", category: "house & furniture" },
    { word: "Stuhl", article: "der", meaning: "chair", category: "house & furniture" },
    { word: "Bett", article: "das", meaning: "bed", category: "house & furniture" },
    { word: "Schrank", article: "der", meaning: "closet", category: "house & furniture" },
    { word: "Sofa", article: "das", meaning: "sofa", category: "house & furniture" },
    { word: "Lampe", article: "die", meaning: "lamp", category: "house & furniture" },
    { word: "Spiegel", article: "der", meaning: "mirror", category: "house & furniture" },
    { word: "Treppe", article: "die", meaning: "stairs", category: "house & furniture" },
    { word: "Garten", article: "der", meaning: "garden", category: "house & furniture" },
    { word: "Balkon", article: "der", meaning: "balcony", category: "house & furniture" },
    { word: "Dach", article: "das", meaning: "roof", category: "house & furniture" },
    { word: "Wand", article: "die", meaning: "wall", category: "house & furniture" },
    { word: "Boden", article: "der", meaning: "floor", category: "house & furniture" },
    { word: "Regal", article: "das", meaning: "shelf", category: "house & furniture" },
    { word: "Teppich", article: "der", meaning: "carpet", category: "house & furniture" },
    { word: "Kühlschrank", article: "der", meaning: "refrigerator", category: "house & furniture" },

    // ===== TRANSPORTATION =====
    { word: "Auto", article: "das", meaning: "car", category: "transportation" },
    { word: "Bus", article: "der", meaning: "bus", category: "transportation" },
    { word: "Zug", article: "der", meaning: "train", category: "transportation" },
    { word: "Fahrrad", article: "das", meaning: "bicycle", category: "transportation" },
    { word: "Flugzeug", article: "das", meaning: "airplane", category: "transportation" },
    { word: "Schiff", article: "das", meaning: "ship", category: "transportation" },
    { word: "Straßenbahn", article: "die", meaning: "tram", category: "transportation" },
    { word: "Taxi", article: "das", meaning: "taxi", category: "transportation" },
    { word: "U-Bahn", article: "die", meaning: "subway", category: "transportation" },
    { word: "Straße", article: "die", meaning: "street", category: "transportation" },
    { word: "Ampel", article: "die", meaning: "traffic light", category: "transportation" },
    { word: "Brücke", article: "die", meaning: "bridge", category: "transportation" },
    { word: "Haltestelle", article: "die", meaning: "stop (bus/tram)", category: "transportation" },
    { word: "Fahrkarte", article: "die", meaning: "ticket", category: "transportation" },
    { word: "Bahnhof", article: "der", meaning: "train station", category: "transportation" },
    { word: "Flughafen", article: "der", meaning: "airport", category: "transportation" },
    { word: "Parkplatz", article: "der", meaning: "parking lot", category: "transportation" },
    { word: "Führerschein", article: "der", meaning: "driver's license", category: "transportation" },
    { word: "Motorrad", article: "das", meaning: "motorcycle", category: "transportation" },
    { word: "Weg", article: "der", meaning: "way", category: "transportation" },
    { word: "Benzin", article: "das", meaning: "gasoline", category: "transportation" },
    { word: "Verkehr", article: "der", meaning: "traffic", category: "transportation" },
    { word: "Autobahn", article: "die", meaning: "highway", category: "transportation" },
    { word: "Kreuzung", article: "die", meaning: "intersection", category: "transportation" },
    { word: "Fahrer", article: "der", meaning: "driver", category: "transportation" },

    // ===== NATURE & WEATHER =====
    { word: "Sonne", article: "die", meaning: "sun", category: "nature & weather" },
    { word: "Mond", article: "der", meaning: "moon", category: "nature & weather" },
    { word: "Stern", article: "der", meaning: "star", category: "nature & weather" },
    { word: "Himmel", article: "der", meaning: "sky", category: "nature & weather" },
    { word: "Wolke", article: "die", meaning: "cloud", category: "nature & weather" },
    { word: "Regen", article: "der", meaning: "rain", category: "nature & weather" },
    { word: "Schnee", article: "der", meaning: "snow", category: "nature & weather" },
    { word: "Wind", article: "der", meaning: "wind", category: "nature & weather" },
    { word: "Wetter", article: "das", meaning: "weather", category: "nature & weather" },
    { word: "Baum", article: "der", meaning: "tree", category: "nature & weather" },
    { word: "Blume", article: "die", meaning: "flower", category: "nature & weather" },
    { word: "Wald", article: "der", meaning: "forest", category: "nature & weather" },
    { word: "Berg", article: "der", meaning: "mountain", category: "nature & weather" },
    { word: "See", article: "der", meaning: "lake", category: "nature & weather" },
    { word: "Meer", article: "das", meaning: "sea", category: "nature & weather" },
    { word: "Fluss", article: "der", meaning: "river", category: "nature & weather" },
    { word: "Strand", article: "der", meaning: "beach", category: "nature & weather" },
    { word: "Insel", article: "die", meaning: "island", category: "nature & weather" },
    { word: "Luft", article: "die", meaning: "air", category: "nature & weather" },
    { word: "Feuer", article: "das", meaning: "fire", category: "nature & weather" },
    { word: "Erde", article: "die", meaning: "earth", category: "nature & weather" },
    { word: "Blatt", article: "das", meaning: "leaf", category: "nature & weather" },
    { word: "Gras", article: "das", meaning: "grass", category: "nature & weather" },
    { word: "Gewitter", article: "das", meaning: "thunderstorm", category: "nature & weather" },
    { word: "Eis", article: "das", meaning: "ice", category: "nature & weather" },

    // ===== SCHOOL & EDUCATION =====
    { word: "Schule", article: "die", meaning: "school", category: "school & education" },
    { word: "Lehrer", article: "der", meaning: "teacher (male)", category: "school & education" },
    { word: "Lehrerin", article: "die", meaning: "teacher (female)", category: "school & education" },
    { word: "Schüler", article: "der", meaning: "student (male)", category: "school & education" },
    { word: "Schülerin", article: "die", meaning: "student (female)", category: "school & education" },
    { word: "Klasse", article: "die", meaning: "class", category: "school & education" },
    { word: "Buch", article: "das", meaning: "book", category: "school & education" },
    { word: "Heft", article: "das", meaning: "notebook", category: "school & education" },
    { word: "Stift", article: "der", meaning: "pen", category: "school & education" },
    { word: "Bleistift", article: "der", meaning: "pencil", category: "school & education" },
    { word: "Tafel", article: "die", meaning: "blackboard", category: "school & education" },
    { word: "Hausaufgabe", article: "die", meaning: "homework", category: "school & education" },
    { word: "Prüfung", article: "die", meaning: "exam", category: "school & education" },
    { word: "Universität", article: "die", meaning: "university", category: "school & education" },
    { word: "Sprache", article: "die", meaning: "language", category: "school & education" },
    { word: "Wort", article: "das", meaning: "word", category: "school & education" },
    { word: "Satz", article: "der", meaning: "sentence", category: "school & education" },
    { word: "Frage", article: "die", meaning: "question", category: "school & education" },
    { word: "Antwort", article: "die", meaning: "answer", category: "school & education" },
    { word: "Aufgabe", article: "die", meaning: "task", category: "school & education" },
    { word: "Kurs", article: "der", meaning: "course", category: "school & education" },
    { word: "Beispiel", article: "das", meaning: "example", category: "school & education" },
    { word: "Übung", article: "die", meaning: "exercise", category: "school & education" },
    { word: "Bibliothek", article: "die", meaning: "library", category: "school & education" },
    { word: "Seite", article: "die", meaning: "page", category: "school & education" },

    // ===== WORK & PROFESSION =====
    { word: "Arbeit", article: "die", meaning: "work", category: "work & profession" },
    { word: "Beruf", article: "der", meaning: "profession", category: "work & profession" },
    { word: "Büro", article: "das", meaning: "office", category: "work & profession" },
    { word: "Chef", article: "der", meaning: "boss", category: "work & profession" },
    { word: "Chefin", article: "die", meaning: "boss (female)", category: "work & profession" },
    { word: "Kollege", article: "der", meaning: "colleague (male)", category: "work & profession" },
    { word: "Kollegin", article: "die", meaning: "colleague (female)", category: "work & profession" },
    { word: "Firma", article: "die", meaning: "company", category: "work & profession" },
    { word: "Polizist", article: "der", meaning: "police officer", category: "work & profession" },
    { word: "Koch", article: "der", meaning: "cook", category: "work & profession" },
    { word: "Bäcker", article: "der", meaning: "baker", category: "work & profession" },
    { word: "Kellner", article: "der", meaning: "waiter", category: "work & profession" },
    { word: "Ingenieur", article: "der", meaning: "engineer", category: "work & profession" },
    { word: "Krankenschwester", article: "die", meaning: "nurse", category: "work & profession" },
    { word: "Friseur", article: "der", meaning: "hairdresser", category: "work & profession" },
    { word: "Mechaniker", article: "der", meaning: "mechanic", category: "work & profession" },
    { word: "Verkäufer", article: "der", meaning: "salesperson", category: "work & profession" },
    { word: "Bauer", article: "der", meaning: "farmer", category: "work & profession" },
    { word: "Termin", article: "der", meaning: "appointment", category: "work & profession" },
    { word: "Gehalt", article: "das", meaning: "salary", category: "work & profession" },
    { word: "Stelle", article: "die", meaning: "position", category: "work & profession" },
    { word: "Vertrag", article: "der", meaning: "contract", category: "work & profession" },
    { word: "Urlaub", article: "der", meaning: "vacation", category: "work & profession" },
    { word: "Pause", article: "die", meaning: "break", category: "work & profession" },
    { word: "Erfahrung", article: "die", meaning: "experience", category: "work & profession" },

    // ===== DAILY LIFE & OBJECTS =====
    { word: "Schlüssel", article: "der", meaning: "key", category: "daily life & objects" },
    { word: "Telefon", article: "das", meaning: "telephone", category: "daily life & objects" },
    { word: "Handy", article: "das", meaning: "cell phone", category: "daily life & objects" },
    { word: "Computer", article: "der", meaning: "computer", category: "daily life & objects" },
    { word: "Tasse", article: "die", meaning: "cup", category: "daily life & objects" },
    { word: "Glas", article: "das", meaning: "glass", category: "daily life & objects" },
    { word: "Teller", article: "der", meaning: "plate", category: "daily life & objects" },
    { word: "Messer", article: "das", meaning: "knife", category: "daily life & objects" },
    { word: "Gabel", article: "die", meaning: "fork", category: "daily life & objects" },
    { word: "Löffel", article: "der", meaning: "spoon", category: "daily life & objects" },
    { word: "Flasche", article: "die", meaning: "bottle", category: "daily life & objects" },
    { word: "Seife", article: "die", meaning: "soap", category: "daily life & objects" },
    { word: "Handtuch", article: "das", meaning: "towel", category: "daily life & objects" },
    { word: "Papier", article: "das", meaning: "paper", category: "daily life & objects" },
    { word: "Schere", article: "die", meaning: "scissors", category: "daily life & objects" },
    { word: "Kerze", article: "die", meaning: "candle", category: "daily life & objects" },
    { word: "Geschenk", article: "das", meaning: "gift", category: "daily life & objects" },
    { word: "Foto", article: "das", meaning: "photo", category: "daily life & objects" },
    { word: "Koffer", article: "der", meaning: "suitcase", category: "daily life & objects" },
    { word: "Dusche", article: "die", meaning: "shower", category: "daily life & objects" },
    { word: "Waschmaschine", article: "die", meaning: "washing machine", category: "daily life & objects" },
    { word: "Batterie", article: "die", meaning: "battery", category: "daily life & objects" },
    { word: "Topf", article: "der", meaning: "pot", category: "daily life & objects" },
    { word: "Pfanne", article: "die", meaning: "pan", category: "daily life & objects" },
    { word: "Dose", article: "die", meaning: "can", category: "daily life & objects" },

    // ===== TIME & CALENDAR =====
    { word: "Tag", article: "der", meaning: "day", category: "time & calendar" },
    { word: "Nacht", article: "die", meaning: "night", category: "time & calendar" },
    { word: "Morgen", article: "der", meaning: "morning", category: "time & calendar" },
    { word: "Abend", article: "der", meaning: "evening", category: "time & calendar" },
    { word: "Mittag", article: "der", meaning: "noon", category: "time & calendar" },
    { word: "Woche", article: "die", meaning: "week", category: "time & calendar" },
    { word: "Monat", article: "der", meaning: "month", category: "time & calendar" },
    { word: "Jahr", article: "das", meaning: "year", category: "time & calendar" },
    { word: "Stunde", article: "die", meaning: "hour", category: "time & calendar" },
    { word: "Minute", article: "die", meaning: "minute", category: "time & calendar" },
    { word: "Sekunde", article: "die", meaning: "second", category: "time & calendar" },
    { word: "Montag", article: "der", meaning: "monday", category: "time & calendar" },
    { word: "Dienstag", article: "der", meaning: "tuesday", category: "time & calendar" },
    { word: "Mittwoch", article: "der", meaning: "wednesday", category: "time & calendar" },
    { word: "Donnerstag", article: "der", meaning: "thursday", category: "time & calendar" },
    { word: "Freitag", article: "der", meaning: "friday", category: "time & calendar" },
    { word: "Samstag", article: "der", meaning: "saturday", category: "time & calendar" },
    { word: "Sonntag", article: "der", meaning: "sunday", category: "time & calendar" },
    { word: "Wochenende", article: "das", meaning: "weekend", category: "time & calendar" },
    { word: "Geburtstag", article: "der", meaning: "birthday", category: "time & calendar" },
    { word: "Feiertag", article: "der", meaning: "holiday", category: "time & calendar" },
    { word: "Frühling", article: "der", meaning: "spring", category: "time & calendar" },
    { word: "Sommer", article: "der", meaning: "summer", category: "time & calendar" },
    { word: "Herbst", article: "der", meaning: "autumn", category: "time & calendar" },
    { word: "Winter", article: "der", meaning: "winter", category: "time & calendar" },

    // ===== CITY & PLACES =====
    { word: "Stadt", article: "die", meaning: "city", category: "city & places" },
    { word: "Dorf", article: "das", meaning: "village", category: "city & places" },
    { word: "Land", article: "das", meaning: "country", category: "city & places" },
    { word: "Platz", article: "der", meaning: "square", category: "city & places" },
    { word: "Kirche", article: "die", meaning: "church", category: "city & places" },
    { word: "Restaurant", article: "das", meaning: "restaurant", category: "city & places" },
    { word: "Hotel", article: "das", meaning: "hotel", category: "city & places" },
    { word: "Museum", article: "das", meaning: "museum", category: "city & places" },
    { word: "Kino", article: "das", meaning: "cinema", category: "city & places" },
    { word: "Theater", article: "das", meaning: "theater", category: "city & places" },
    { word: "Park", article: "der", meaning: "park", category: "city & places" },
    { word: "Bank", article: "die", meaning: "bank", category: "city & places" },
    { word: "Post", article: "die", meaning: "post office", category: "city & places" },
    { word: "Supermarkt", article: "der", meaning: "supermarket", category: "city & places" },
    { word: "Bäckerei", article: "die", meaning: "bakery", category: "city & places" },
    { word: "Markt", article: "der", meaning: "market", category: "city & places" },
    { word: "Café", article: "das", meaning: "café", category: "city & places" },
    { word: "Tankstelle", article: "die", meaning: "gas station", category: "city & places" },
    { word: "Rathaus", article: "das", meaning: "town hall", category: "city & places" },
    { word: "Schwimmbad", article: "das", meaning: "swimming pool", category: "city & places" },
    { word: "Spielplatz", article: "der", meaning: "playground", category: "city & places" },
    { word: "Stadtzentrum", article: "das", meaning: "city center", category: "city & places" },
    { word: "Polizei", article: "die", meaning: "police", category: "city & places" },
    { word: "Feuerwehr", article: "die", meaning: "fire department", category: "city & places" },
    { word: "Botschaft", article: "die", meaning: "embassy", category: "city & places" },

    // ===== HOBBIES & SPORTS =====
    { word: "Sport", article: "der", meaning: "sport", category: "hobbies & sports" },
    { word: "Fußball", article: "der", meaning: "soccer", category: "hobbies & sports" },
    { word: "Tennis", article: "das", meaning: "tennis", category: "hobbies & sports" },
    { word: "Schwimmen", article: "das", meaning: "swimming", category: "hobbies & sports" },
    { word: "Musik", article: "die", meaning: "music", category: "hobbies & sports" },
    { word: "Gitarre", article: "die", meaning: "guitar", category: "hobbies & sports" },
    { word: "Klavier", article: "das", meaning: "piano", category: "hobbies & sports" },
    { word: "Lied", article: "das", meaning: "song", category: "hobbies & sports" },
    { word: "Tanz", article: "der", meaning: "dance", category: "hobbies & sports" },
    { word: "Film", article: "der", meaning: "film", category: "hobbies & sports" },
    { word: "Spiel", article: "das", meaning: "game", category: "hobbies & sports" },
    { word: "Ball", article: "der", meaning: "ball", category: "hobbies & sports" },
    { word: "Hobby", article: "das", meaning: "hobby", category: "hobbies & sports" },
    { word: "Laufen", article: "das", meaning: "running", category: "hobbies & sports" },
    { word: "Mannschaft", article: "die", meaning: "team", category: "hobbies & sports" },
    { word: "Wandern", article: "das", meaning: "hiking", category: "hobbies & sports" },
    { word: "Rad", article: "das", meaning: "wheel/cycling", category: "hobbies & sports" },
    { word: "Karte", article: "die", meaning: "card", category: "hobbies & sports" },
    { word: "Konzert", article: "das", meaning: "concert", category: "hobbies & sports" },
    { word: "Bild", article: "das", meaning: "picture", category: "hobbies & sports" },
    { word: "Malen", article: "das", meaning: "painting", category: "hobbies & sports" },
    { word: "Kochen", article: "das", meaning: "cooking", category: "hobbies & sports" },
    { word: "Lesen", article: "das", meaning: "reading", category: "hobbies & sports" },
    { word: "Verein", article: "der", meaning: "club", category: "hobbies & sports" },
    { word: "Yoga", article: "das", meaning: "yoga", category: "hobbies & sports" },

    // ===== EMOTIONS & ADJECTIVES (as nouns) =====
    { word: "Freude", article: "die", meaning: "joy", category: "emotions & adjectives" },
    { word: "Angst", article: "die", meaning: "fear", category: "emotions & adjectives" },
    { word: "Liebe", article: "die", meaning: "love", category: "emotions & adjectives" },
    { word: "Glück", article: "das", meaning: "happiness", category: "emotions & adjectives" },
    { word: "Trauer", article: "die", meaning: "sadness", category: "emotions & adjectives" },
    { word: "Wut", article: "die", meaning: "anger", category: "emotions & adjectives" },
    { word: "Hoffnung", article: "die", meaning: "hope", category: "emotions & adjectives" },
    { word: "Sorge", article: "die", meaning: "worry", category: "emotions & adjectives" },
    { word: "Überraschung", article: "die", meaning: "surprise", category: "emotions & adjectives" },
    { word: "Langeweile", article: "die", meaning: "boredom", category: "emotions & adjectives" },
    { word: "Ruhe", article: "die", meaning: "calm", category: "emotions & adjectives" },
    { word: "Stress", article: "der", meaning: "stress", category: "emotions & adjectives" },
    { word: "Spaß", article: "der", meaning: "fun", category: "emotions & adjectives" },
    { word: "Mut", article: "der", meaning: "courage", category: "emotions & adjectives" },
    { word: "Geduld", article: "die", meaning: "patience", category: "emotions & adjectives" },
    { word: "Hunger", article: "der", meaning: "hunger", category: "emotions & adjectives" },
    { word: "Durst", article: "der", meaning: "thirst", category: "emotions & adjectives" },
    { word: "Müdigkeit", article: "die", meaning: "tiredness", category: "emotions & adjectives" },
    { word: "Lust", article: "die", meaning: "desire", category: "emotions & adjectives" },
    { word: "Interesse", article: "das", meaning: "interest", category: "emotions & adjectives" },
    { word: "Vertrauen", article: "das", meaning: "trust", category: "emotions & adjectives" },
    { word: "Stolz", article: "der", meaning: "pride", category: "emotions & adjectives" },
    { word: "Einsamkeit", article: "die", meaning: "loneliness", category: "emotions & adjectives" },
    { word: "Freiheit", article: "die", meaning: "freedom", category: "emotions & adjectives" },
    { word: "Zufriedenheit", article: "die", meaning: "contentment", category: "emotions & adjectives" },

    // ===== NUMBERS & QUANTITIES (as nouns) =====
    { word: "Zahl", article: "die", meaning: "number", category: "numbers & quantities" },
    { word: "Hälfte", article: "die", meaning: "half", category: "numbers & quantities" },
    { word: "Paar", article: "das", meaning: "pair", category: "numbers & quantities" },
    { word: "Dutzend", article: "das", meaning: "dozen", category: "numbers & quantities" },
    { word: "Prozent", article: "das", meaning: "percent", category: "numbers & quantities" },
    { word: "Menge", article: "die", meaning: "amount", category: "numbers & quantities" },
    { word: "Stück", article: "das", meaning: "piece", category: "numbers & quantities" },
    { word: "Meter", article: "der", meaning: "meter", category: "numbers & quantities" },
    { word: "Kilometer", article: "der", meaning: "kilometer", category: "numbers & quantities" },
    { word: "Kilogramm", article: "das", meaning: "kilogram", category: "numbers & quantities" },
    { word: "Liter", article: "der", meaning: "liter", category: "numbers & quantities" },
    { word: "Gramm", article: "das", meaning: "gram", category: "numbers & quantities" },
    { word: "Grad", article: "der", meaning: "degree", category: "numbers & quantities" },
    { word: "Gewicht", article: "das", meaning: "weight", category: "numbers & quantities" },
    { word: "Größe", article: "die", meaning: "size", category: "numbers & quantities" },
    { word: "Länge", article: "die", meaning: "length", category: "numbers & quantities" },
    { word: "Breite", article: "die", meaning: "width", category: "numbers & quantities" },
    { word: "Höhe", article: "die", meaning: "height", category: "numbers & quantities" },
    { word: "Summe", article: "die", meaning: "sum", category: "numbers & quantities" },
    { word: "Nummer", article: "die", meaning: "number (identifier)", category: "numbers & quantities" },
    { word: "Mal", article: "das", meaning: "time (occurrence)", category: "numbers & quantities" },
    { word: "Teil", article: "der", meaning: "part", category: "numbers & quantities" },
    { word: "Drittel", article: "das", meaning: "third", category: "numbers & quantities" },
    { word: "Viertel", article: "das", meaning: "quarter", category: "numbers & quantities" },
    { word: "Rest", article: "der", meaning: "remainder", category: "numbers & quantities" },

    // ===== COMMUNICATION & MEDIA =====
    { word: "Brief", article: "der", meaning: "letter", category: "communication & media" },
    { word: "E-Mail", article: "die", meaning: "email", category: "communication & media" },
    { word: "Nachricht", article: "die", meaning: "message", category: "communication & media" },
    { word: "Zeitung", article: "die", meaning: "newspaper", category: "communication & media" },
    { word: "Zeitschrift", article: "die", meaning: "magazine", category: "communication & media" },
    { word: "Fernsehen", article: "das", meaning: "television", category: "communication & media" },
    { word: "Radio", article: "das", meaning: "radio", category: "communication & media" },
    { word: "Internet", article: "das", meaning: "internet", category: "communication & media" },
    { word: "Gespräch", article: "das", meaning: "conversation", category: "communication & media" },
    { word: "Anruf", article: "der", meaning: "phone call", category: "communication & media" },
    { word: "Information", article: "die", meaning: "information", category: "communication & media" },
    { word: "Name", article: "der", meaning: "name", category: "communication & media" },
    { word: "Adresse", article: "die", meaning: "address", category: "communication & media" },
    { word: "Text", article: "der", meaning: "text", category: "communication & media" },
    { word: "Programm", article: "das", meaning: "program", category: "communication & media" },
    { word: "Sendung", article: "die", meaning: "broadcast", category: "communication & media" },
    { word: "Stimme", article: "die", meaning: "voice", category: "communication & media" },
    { word: "Geschichte", article: "die", meaning: "story", category: "communication & media" },
    { word: "Meinung", article: "die", meaning: "opinion", category: "communication & media" },
    { word: "Formulär", article: "das", meaning: "form", category: "communication & media" },
    { word: "Unterschrift", article: "die", meaning: "signature", category: "communication & media" },
    { word: "Dokument", article: "das", meaning: "document", category: "communication & media" },
    { word: "Passwort", article: "das", meaning: "password", category: "communication & media" },
    { word: "Bildschirm", article: "der", meaning: "screen", category: "communication & media" },
    { word: "Drucker", article: "der", meaning: "printer", category: "communication & media" },

    // ===== SHOPPING & MONEY =====
    { word: "Geld", article: "das", meaning: "money", category: "shopping & money" },
    { word: "Preis", article: "der", meaning: "price", category: "shopping & money" },
    { word: "Euro", article: "der", meaning: "euro", category: "shopping & money" },
    { word: "Cent", article: "der", meaning: "cent", category: "shopping & money" },
    { word: "Kasse", article: "die", meaning: "cash register", category: "shopping & money" },
    { word: "Rechnung", article: "die", meaning: "bill", category: "shopping & money" },
    { word: "Geschäft", article: "das", meaning: "shop", category: "shopping & money" },
    { word: "Einkauf", article: "der", meaning: "purchase", category: "shopping & money" },
    { word: "Angebot", article: "das", meaning: "offer", category: "shopping & money" },
    { word: "Kunde", article: "der", meaning: "customer (male)", category: "shopping & money" },
    { word: "Kundin", article: "die", meaning: "customer (female)", category: "shopping & money" },
    { word: "Quittung", article: "die", meaning: "receipt", category: "shopping & money" },
    { word: "Rabatt", article: "der", meaning: "discount", category: "shopping & money" },
    { word: "Konto", article: "das", meaning: "account", category: "shopping & money" },
    { word: "Münze", article: "die", meaning: "coin", category: "shopping & money" },
    { word: "Schein", article: "der", meaning: "banknote", category: "shopping & money" },
    { word: "Geldbeutel", article: "der", meaning: "wallet", category: "shopping & money" },
    { word: "Kreditkarte", article: "die", meaning: "credit card", category: "shopping & money" },
    { word: "Sonderangebot", article: "das", meaning: "special offer", category: "shopping & money" },
    { word: "Marke", article: "die", meaning: "brand", category: "shopping & money" },
    { word: "Tüte", article: "die", meaning: "bag (plastic)", category: "shopping & money" },
    { word: "Ware", article: "die", meaning: "goods", category: "shopping & money" },
    { word: "Einkaufswagen", article: "der", meaning: "shopping cart", category: "shopping & money" },
    { word: "Umtausch", article: "der", meaning: "exchange", category: "shopping & money" },
    { word: "Steuer", article: "die", meaning: "tax", category: "shopping & money" },

    // ===== TRAVEL & VACATION =====
    { word: "Reise", article: "die", meaning: "trip", category: "travel & vacation" },
    { word: "Ferien", article: "die", meaning: "vacation", category: "travel & vacation" },
    { word: "Pass", article: "der", meaning: "passport", category: "travel & vacation" },
    { word: "Visum", article: "das", meaning: "visa", category: "travel & vacation" },
    { word: "Gepäck", article: "das", meaning: "luggage", category: "travel & vacation" },
    { word: "Reservierung", article: "die", meaning: "reservation", category: "travel & vacation" },
    { word: "Ausflug", article: "der", meaning: "excursion", category: "travel & vacation" },
    { word: "Landkarte", article: "die", meaning: "map", category: "travel & vacation" },
    { word: "Tourist", article: "der", meaning: "tourist", category: "travel & vacation" },
    { word: "Unterkunft", article: "die", meaning: "accommodation", category: "travel & vacation" },
    { word: "Ausland", article: "das", meaning: "abroad", category: "travel & vacation" },
    { word: "Grenze", article: "die", meaning: "border", category: "travel & vacation" },
    { word: "Abfahrt", article: "die", meaning: "departure", category: "travel & vacation" },
    { word: "Ankunft", article: "die", meaning: "arrival", category: "travel & vacation" },
    { word: "Rückfahrt", article: "die", meaning: "return trip", category: "travel & vacation" },
    { word: "Sehenswürdigkeit", article: "die", meaning: "sight (attraction)", category: "travel & vacation" },
    { word: "Postkarte", article: "die", meaning: "postcard", category: "travel & vacation" },
    { word: "Souvenir", article: "das", meaning: "souvenir", category: "travel & vacation" },
    { word: "Sonnencreme", article: "die", meaning: "sunscreen", category: "travel & vacation" },
    { word: "Camping", article: "das", meaning: "camping", category: "travel & vacation" },
    { word: "Zelt", article: "das", meaning: "tent", category: "travel & vacation" },
    { word: "Hafen", article: "der", meaning: "harbor", category: "travel & vacation" },
    { word: "Abflug", article: "der", meaning: "flight departure", category: "travel & vacation" },
    { word: "Verspätung", article: "die", meaning: "delay", category: "travel & vacation" },
    { word: "Fahrplan", article: "der", meaning: "timetable", category: "travel & vacation" },

    // ===== COLORS (as nouns) =====
    { word: "Rot", article: "das", meaning: "red", category: "colors" },
    { word: "Blau", article: "das", meaning: "blue", category: "colors" },
    { word: "Grün", article: "das", meaning: "green", category: "colors" },
    { word: "Gelb", article: "das", meaning: "yellow", category: "colors" },
    { word: "Schwarz", article: "das", meaning: "black", category: "colors" },
    { word: "Weiß", article: "das", meaning: "white", category: "colors" },
    { word: "Grau", article: "das", meaning: "gray", category: "colors" },
    { word: "Braun", article: "das", meaning: "brown", category: "colors" },
    { word: "Rosa", article: "das", meaning: "pink", category: "colors" },
    { word: "Lila", article: "das", meaning: "purple", category: "colors" },
    { word: "Dunkelrot", article: "das", meaning: "dark red", category: "colors" },
    { word: "Gold", article: "das", meaning: "gold", category: "colors" },
    { word: "Silber", article: "das", meaning: "silver", category: "colors" },
    { word: "Farbe", article: "die", meaning: "color", category: "colors" },
    { word: "Hellblau", article: "das", meaning: "light blue", category: "colors" },
    { word: "Dunkelgrün", article: "das", meaning: "dark green", category: "colors" },
    { word: "Violett", article: "das", meaning: "violet", category: "colors" },
    { word: "Türkis", article: "das", meaning: "turquoise", category: "colors" },
    { word: "Beige", article: "das", meaning: "beige", category: "colors" },
    { word: "Hellgrau", article: "das", meaning: "light gray", category: "colors" },

    // ===== VERBS =====
    { word: "gehen", meaning: "to go", category: "verbs", type: "verb" },
    { word: "kommen", meaning: "to come", category: "verbs", type: "verb" },
    { word: "machen", meaning: "to make / to do", category: "verbs", type: "verb" },
    { word: "haben", meaning: "to have", category: "verbs", type: "verb" },
    { word: "sein", meaning: "to be", category: "verbs", type: "verb" },
    { word: "werden", meaning: "to become", category: "verbs", type: "verb" },
    { word: "können", meaning: "to be able to / can", category: "verbs", type: "verb" },
    { word: "müssen", meaning: "to have to / must", category: "verbs", type: "verb" },
    { word: "sollen", meaning: "to should", category: "verbs", type: "verb" },
    { word: "wollen", meaning: "to want", category: "verbs", type: "verb" },
    { word: "dürfen", meaning: "to be allowed to / may", category: "verbs", type: "verb" },
    { word: "mögen", meaning: "to like", category: "verbs", type: "verb" },
    { word: "essen", meaning: "to eat", category: "verbs", type: "verb" },
    { word: "trinken", meaning: "to drink", category: "verbs", type: "verb" },
    { word: "schlafen", meaning: "to sleep", category: "verbs", type: "verb" },
    { word: "sprechen", meaning: "to speak", category: "verbs", type: "verb" },
    { word: "lesen", meaning: "to read", category: "verbs", type: "verb" },
    { word: "schreiben", meaning: "to write", category: "verbs", type: "verb" },
    { word: "hören", meaning: "to hear / to listen", category: "verbs", type: "verb" },
    { word: "sehen", meaning: "to see", category: "verbs", type: "verb" },
    { word: "verstehen", meaning: "to understand", category: "verbs", type: "verb" },
    { word: "lernen", meaning: "to learn", category: "verbs", type: "verb" },
    { word: "arbeiten", meaning: "to work", category: "verbs", type: "verb" },
    { word: "spielen", meaning: "to play", category: "verbs", type: "verb" },
    { word: "fahren", meaning: "to drive / to travel", category: "verbs", type: "verb" },
    { word: "laufen", meaning: "to run / to walk", category: "verbs", type: "verb" },
    { word: "schwimmen", meaning: "to swim", category: "verbs", type: "verb" },
    { word: "fliegen", meaning: "to fly", category: "verbs", type: "verb" },
    { word: "kaufen", meaning: "to buy", category: "verbs", type: "verb" },
    { word: "verkaufen", meaning: "to sell", category: "verbs", type: "verb" },
    { word: "bezahlen", meaning: "to pay", category: "verbs", type: "verb" },
    { word: "kosten", meaning: "to cost", category: "verbs", type: "verb" },
    { word: "brauchen", meaning: "to need", category: "verbs", type: "verb" },
    { word: "finden", meaning: "to find", category: "verbs", type: "verb" },
    { word: "suchen", meaning: "to search / to look for", category: "verbs", type: "verb" },
    { word: "geben", meaning: "to give", category: "verbs", type: "verb" },
    { word: "nehmen", meaning: "to take", category: "verbs", type: "verb" },
    { word: "bringen", meaning: "to bring", category: "verbs", type: "verb" },
    { word: "helfen", meaning: "to help", category: "verbs", type: "verb" },
    { word: "fragen", meaning: "to ask", category: "verbs", type: "verb" },
    { word: "antworten", meaning: "to answer", category: "verbs", type: "verb" },
    { word: "sagen", meaning: "to say", category: "verbs", type: "verb" },
    { word: "erzählen", meaning: "to tell / to narrate", category: "verbs", type: "verb" },
    { word: "wissen", meaning: "to know (a fact)", category: "verbs", type: "verb" },
    { word: "kennen", meaning: "to know (a person/place)", category: "verbs", type: "verb" },
    { word: "denken", meaning: "to think", category: "verbs", type: "verb" },
    { word: "glauben", meaning: "to believe", category: "verbs", type: "verb" },
    { word: "hoffen", meaning: "to hope", category: "verbs", type: "verb" },
    { word: "warten", meaning: "to wait", category: "verbs", type: "verb" },
    { word: "beginnen", meaning: "to begin", category: "verbs", type: "verb" },
    { word: "aufhören", meaning: "to stop", category: "verbs", type: "verb" },
    { word: "öffnen", meaning: "to open", category: "verbs", type: "verb" },
    { word: "schließen", meaning: "to close", category: "verbs", type: "verb" },
    { word: "waschen", meaning: "to wash", category: "verbs", type: "verb" },
    { word: "putzen", meaning: "to clean", category: "verbs", type: "verb" },
    { word: "kochen", meaning: "to cook", category: "verbs", type: "verb" },
    { word: "backen", meaning: "to bake", category: "verbs", type: "verb" },
    { word: "tanzen", meaning: "to dance", category: "verbs", type: "verb" },
    { word: "singen", meaning: "to sing", category: "verbs", type: "verb" },
    { word: "malen", meaning: "to paint / to draw", category: "verbs", type: "verb" },
    { word: "wohnen", meaning: "to live (reside)", category: "verbs", type: "verb" },
    { word: "leben", meaning: "to live (be alive)", category: "verbs", type: "verb" },
    { word: "lieben", meaning: "to love", category: "verbs", type: "verb" },
    { word: "hassen", meaning: "to hate", category: "verbs", type: "verb" },
    { word: "lachen", meaning: "to laugh", category: "verbs", type: "verb" },
    { word: "weinen", meaning: "to cry", category: "verbs", type: "verb" },
    { word: "sitzen", meaning: "to sit", category: "verbs", type: "verb" },
    { word: "stehen", meaning: "to stand", category: "verbs", type: "verb" },
    { word: "liegen", meaning: "to lie (down)", category: "verbs", type: "verb" },
    { word: "tragen", meaning: "to carry / to wear", category: "verbs", type: "verb" },
    { word: "ziehen", meaning: "to pull / to move", category: "verbs", type: "verb" },
    { word: "drücken", meaning: "to push / to press", category: "verbs", type: "verb" },
    { word: "fallen", meaning: "to fall", category: "verbs", type: "verb" },
    { word: "aufstehen", meaning: "to get up", category: "verbs", type: "verb" },
    { word: "ankommen", meaning: "to arrive", category: "verbs", type: "verb" },
    { word: "abfahren", meaning: "to depart", category: "verbs", type: "verb" },
    { word: "einladen", meaning: "to invite", category: "verbs", type: "verb" },
    { word: "besuchen", meaning: "to visit", category: "verbs", type: "verb" },
    { word: "treffen", meaning: "to meet", category: "verbs", type: "verb" },
    { word: "anrufen", meaning: "to call (phone)", category: "verbs", type: "verb" },
    { word: "schicken", meaning: "to send", category: "verbs", type: "verb" },
    { word: "bekommen", meaning: "to receive / to get", category: "verbs", type: "verb" },
    { word: "vergessen", meaning: "to forget", category: "verbs", type: "verb" },
    { word: "erinnern", meaning: "to remember", category: "verbs", type: "verb" },
    { word: "versuchen", meaning: "to try", category: "verbs", type: "verb" },
    { word: "zeigen", meaning: "to show", category: "verbs", type: "verb" },
    { word: "erklären", meaning: "to explain", category: "verbs", type: "verb" },
    { word: "ändern", meaning: "to change", category: "verbs", type: "verb" },
    { word: "reparieren", meaning: "to repair", category: "verbs", type: "verb" },
    { word: "bestellen", meaning: "to order", category: "verbs", type: "verb" },
    { word: "reservieren", meaning: "to reserve", category: "verbs", type: "verb" },
    { word: "empfehlen", meaning: "to recommend", category: "verbs", type: "verb" },
    { word: "benutzen", meaning: "to use", category: "verbs", type: "verb" },
    { word: "gefallen", meaning: "to please / to like", category: "verbs", type: "verb" },
    { word: "gehören", meaning: "to belong to", category: "verbs", type: "verb" },
    { word: "dauern", meaning: "to last / to take (time)", category: "verbs", type: "verb" },
    { word: "stimmen", meaning: "to be correct", category: "verbs", type: "verb" },
    { word: "bedeuten", meaning: "to mean", category: "verbs", type: "verb" },
    { word: "übersetzen", meaning: "to translate", category: "verbs", type: "verb" },
    { word: "wiederholen", meaning: "to repeat", category: "verbs", type: "verb" },

    // ===== ADJECTIVES =====
    { word: "groß", meaning: "big / tall", category: "adjectives", type: "adjective" },
    { word: "klein", meaning: "small / short", category: "adjectives", type: "adjective" },
    { word: "gut", meaning: "good", category: "adjectives", type: "adjective" },
    { word: "schlecht", meaning: "bad", category: "adjectives", type: "adjective" },
    { word: "schön", meaning: "beautiful", category: "adjectives", type: "adjective" },
    { word: "hässlich", meaning: "ugly", category: "adjectives", type: "adjective" },
    { word: "alt", meaning: "old", category: "adjectives", type: "adjective" },
    { word: "jung", meaning: "young", category: "adjectives", type: "adjective" },
    { word: "neu", meaning: "new", category: "adjectives", type: "adjective" },
    { word: "schnell", meaning: "fast", category: "adjectives", type: "adjective" },
    { word: "langsam", meaning: "slow", category: "adjectives", type: "adjective" },
    { word: "warm", meaning: "warm", category: "adjectives", type: "adjective" },
    { word: "kalt", meaning: "cold", category: "adjectives", type: "adjective" },
    { word: "heiß", meaning: "hot", category: "adjectives", type: "adjective" },
    { word: "lang", meaning: "long", category: "adjectives", type: "adjective" },
    { word: "kurz", meaning: "short", category: "adjectives", type: "adjective" },
    { word: "schwer", meaning: "heavy / difficult", category: "adjectives", type: "adjective" },
    { word: "leicht", meaning: "light / easy", category: "adjectives", type: "adjective" },
    { word: "teuer", meaning: "expensive", category: "adjectives", type: "adjective" },
    { word: "billig", meaning: "cheap", category: "adjectives", type: "adjective" },
    { word: "richtig", meaning: "correct / right", category: "adjectives", type: "adjective" },
    { word: "falsch", meaning: "wrong / false", category: "adjectives", type: "adjective" },
    { word: "wichtig", meaning: "important", category: "adjectives", type: "adjective" },
    { word: "interessant", meaning: "interesting", category: "adjectives", type: "adjective" },
    { word: "langweilig", meaning: "boring", category: "adjectives", type: "adjective" },
    { word: "lustig", meaning: "funny", category: "adjectives", type: "adjective" },
    { word: "traurig", meaning: "sad", category: "adjectives", type: "adjective" },
    { word: "glücklich", meaning: "happy", category: "adjectives", type: "adjective" },
    { word: "müde", meaning: "tired", category: "adjectives", type: "adjective" },
    { word: "krank", meaning: "sick", category: "adjectives", type: "adjective" },
    { word: "gesund", meaning: "healthy", category: "adjectives", type: "adjective" },
    { word: "hungrig", meaning: "hungry", category: "adjectives", type: "adjective" },
    { word: "durstig", meaning: "thirsty", category: "adjectives", type: "adjective" },
    { word: "leer", meaning: "empty", category: "adjectives", type: "adjective" },
    { word: "voll", meaning: "full", category: "adjectives", type: "adjective" },
    { word: "offen", meaning: "open", category: "adjectives", type: "adjective" },
    { word: "geschlossen", meaning: "closed", category: "adjectives", type: "adjective" },
    { word: "dunkel", meaning: "dark", category: "adjectives", type: "adjective" },
    { word: "hell", meaning: "bright / light", category: "adjectives", type: "adjective" },
    { word: "laut", meaning: "loud", category: "adjectives", type: "adjective" },
    { word: "leise", meaning: "quiet", category: "adjectives", type: "adjective" },
    { word: "nett", meaning: "nice / kind", category: "adjectives", type: "adjective" },
    { word: "freundlich", meaning: "friendly", category: "adjectives", type: "adjective" },
    { word: "böse", meaning: "angry / evil", category: "adjectives", type: "adjective" },
    { word: "möglich", meaning: "possible", category: "adjectives", type: "adjective" },
    { word: "fertig", meaning: "finished / ready", category: "adjectives", type: "adjective" },
    { word: "frei", meaning: "free", category: "adjectives", type: "adjective" },
    { word: "schmutzig", meaning: "dirty", category: "adjectives", type: "adjective" },
    { word: "sauber", meaning: "clean", category: "adjectives", type: "adjective" },
    { word: "trocken", meaning: "dry", category: "adjectives", type: "adjective" },

    // ===== ADVERBS =====
    { word: "hier", meaning: "here", category: "adverbs", type: "adverb" },
    { word: "dort", meaning: "there", category: "adverbs", type: "adverb" },
    { word: "heute", meaning: "today", category: "adverbs", type: "adverb" },
    { word: "morgen", meaning: "tomorrow", category: "adverbs", type: "adverb" },
    { word: "gestern", meaning: "yesterday", category: "adverbs", type: "adverb" },
    { word: "jetzt", meaning: "now", category: "adverbs", type: "adverb" },
    { word: "dann", meaning: "then", category: "adverbs", type: "adverb" },
    { word: "immer", meaning: "always", category: "adverbs", type: "adverb" },
    { word: "nie", meaning: "never", category: "adverbs", type: "adverb" },
    { word: "oft", meaning: "often", category: "adverbs", type: "adverb" },
    { word: "manchmal", meaning: "sometimes", category: "adverbs", type: "adverb" },
    { word: "schon", meaning: "already", category: "adverbs", type: "adverb" },
    { word: "noch", meaning: "still / yet", category: "adverbs", type: "adverb" },
    { word: "sehr", meaning: "very", category: "adverbs", type: "adverb" },
    { word: "auch", meaning: "also / too", category: "adverbs", type: "adverb" },
    { word: "nur", meaning: "only", category: "adverbs", type: "adverb" },
    { word: "vielleicht", meaning: "maybe / perhaps", category: "adverbs", type: "adverb" },
    { word: "gern", meaning: "gladly / with pleasure", category: "adverbs", type: "adverb" },
    { word: "zusammen", meaning: "together", category: "adverbs", type: "adverb" },
    { word: "allein", meaning: "alone", category: "adverbs", type: "adverb" },
    { word: "bald", meaning: "soon", category: "adverbs", type: "adverb" },
    { word: "fast", meaning: "almost", category: "adverbs", type: "adverb" },
    { word: "genug", meaning: "enough", category: "adverbs", type: "adverb" },
    { word: "wieder", meaning: "again", category: "adverbs", type: "adverb" },
    { word: "draußen", meaning: "outside", category: "adverbs", type: "adverb" },

    // ===== PREPOSITIONS =====
    { word: "mit", meaning: "with", category: "prepositions", type: "preposition" },
    { word: "ohne", meaning: "without", category: "prepositions", type: "preposition" },
    { word: "für", meaning: "for", category: "prepositions", type: "preposition" },
    { word: "gegen", meaning: "against", category: "prepositions", type: "preposition" },
    { word: "aus", meaning: "from / out of", category: "prepositions", type: "preposition" },
    { word: "bei", meaning: "at / near", category: "prepositions", type: "preposition" },
    { word: "nach", meaning: "after / to", category: "prepositions", type: "preposition" },
    { word: "seit", meaning: "since / for (time)", category: "prepositions", type: "preposition" },
    { word: "von", meaning: "from / of", category: "prepositions", type: "preposition" },
    { word: "zu", meaning: "to", category: "prepositions", type: "preposition" },
    { word: "in", meaning: "in / into", category: "prepositions", type: "preposition" },
    { word: "an", meaning: "at / on (vertical)", category: "prepositions", type: "preposition" },
    { word: "auf", meaning: "on / onto", category: "prepositions", type: "preposition" },
    { word: "über", meaning: "over / about", category: "prepositions", type: "preposition" },
    { word: "unter", meaning: "under / below", category: "prepositions", type: "preposition" },

    // ===== CONJUNCTIONS =====
    { word: "und", meaning: "and", category: "conjunctions", type: "conjunction" },
    { word: "oder", meaning: "or", category: "conjunctions", type: "conjunction" },
    { word: "aber", meaning: "but", category: "conjunctions", type: "conjunction" },
    { word: "weil", meaning: "because", category: "conjunctions", type: "conjunction" },
    { word: "wenn", meaning: "if / when", category: "conjunctions", type: "conjunction" },
    { word: "dass", meaning: "that", category: "conjunctions", type: "conjunction" },
    { word: "obwohl", meaning: "although", category: "conjunctions", type: "conjunction" },
    { word: "denn", meaning: "because / for", category: "conjunctions", type: "conjunction" },
    { word: "sondern", meaning: "but rather", category: "conjunctions", type: "conjunction" },
    { word: "bevor", meaning: "before", category: "conjunctions", type: "conjunction" },
];
