const A2_WORDS = [
    // ===== NOUNS =====
    { word: "Erfolg", article: "der", meaning: "success", category: "work & profession" },
    { word: "Fehler", article: "der", meaning: "mistake", category: "school & education" },
    { word: "Grund", article: "der", meaning: "reason", category: "communication & media" },
    { word: "Ort", article: "der", meaning: "place", category: "city & places" },
    { word: "Wunsch", article: "der", meaning: "wish", category: "emotions & adjectives" },
    { word: "Müll", article: "der", meaning: "trash", category: "house & furniture" },
    { word: "Zweifel", article: "der", meaning: "doubt", category: "emotions & adjectives" },
    { word: "Vertrag", article: "der", meaning: "contract", category: "work & profession" },
    { word: "Lohn", article: "der", meaning: "wage / salary", category: "work & profession" },
    { word: "Zuschauer", article: "der", meaning: "spectator", category: "hobbies & sports" },
    { word: "Kunde", article: "der", meaning: "customer", category: "shopping & money" },
    { word: "Bildschirm", article: "der", meaning: "screen", category: "communication & media" },
    { word: "Drucker", article: "der", meaning: "printer", category: "work & profession" },
    { word: "Verkehr", article: "der", meaning: "traffic", category: "transportation" },
    { word: "Anfang", article: "der", meaning: "beginning", category: "time & calendar" },
    
    { word: "Meinung", article: "die", meaning: "opinion", category: "communication & media" },
    { word: "Entscheidung", article: "die", meaning: "decision", category: "daily life & objects" },
    { word: "Erfahrung", article: "die", meaning: "experience", category: "school & education" },
    { word: "Wahrheit", article: "die", meaning: "truth", category: "communication & media" },
    { word: "Krankheit", article: "die", meaning: "illness", category: "body & health" },
    { word: "Möglichkeit", article: "die", meaning: "possibility", category: "daily life & objects" },
    { word: "Regel", article: "die", meaning: "rule", category: "school & education" },
    { word: "Angst", article: "die", meaning: "fear", category: "emotions & adjectives" },
    { word: "Bedeutung", article: "die", meaning: "meaning", category: "school & education" },
    { word: "Grenze", article: "die", meaning: "border / limit", category: "travel & vacation" },
    { word: "Umwelt", article: "die", meaning: "environment", category: "nature & weather" },
    { word: "Wirtschaft", article: "die", meaning: "economy", category: "work & profession" },
    { word: "Zukunft", article: "die", meaning: "future", category: "time & calendar" },
    { word: "Sicherheit", article: "die", meaning: "security", category: "daily life & objects" },
    { word: "Gesundheit", article: "die", meaning: "health", category: "body & health" },

    { word: "Ziel", article: "das", meaning: "goal", category: "school & education" },
    { word: "Ergebnis", article: "das", meaning: "result", category: "school & education" },
    { word: "Gesetz", article: "das", meaning: "law", category: "work & profession" },
    { word: "Gefühl", article: "das", meaning: "feeling", category: "emotions & adjectives" },
    { word: "Gespräch", article: "das", meaning: "conversation", category: "communication & media" },
    { word: "Thema", article: "das", meaning: "topic", category: "communication & media" },
    { word: "Angebot", article: "das", meaning: "offer", category: "shopping & money" },
    { word: "Verhalten", article: "das", meaning: "behavior", category: "daily life & objects" },
    { word: "Geheimnis", article: "das", meaning: "secret", category: "communication & media" },
    { word: "Gerät", article: "das", meaning: "device", category: "communication & media" },
    { word: "Werkzeug", article: "das", meaning: "tool", category: "work & profession" },
    { word: "Zeichen", article: "das", meaning: "sign", category: "communication & media" },
    { word: "Mitglied", article: "das", meaning: "member", category: "family & people" },
    { word: "System", article: "das", meaning: "system", category: "work & profession" },
    { word: "Interesse", article: "das", meaning: "interest", category: "hobbies & sports" },

    // ===== VERBS =====
    { word: "erinnern", meaning: "to remember", category: "verbs", type: "verb" },
    { word: "entscheiden", meaning: "to decide", category: "verbs", type: "verb" },
    { word: "erzählen", meaning: "to tell / narrate", category: "verbs", type: "verb" },
    { word: "versprechen", meaning: "to promise", category: "verbs", type: "verb" },
    { word: "erwarten", meaning: "to expect", category: "verbs", type: "verb" },
    { word: "passieren", meaning: "to happen", category: "verbs", type: "verb" },
    { word: "bemerken", meaning: "to notice", category: "verbs", type: "verb" },
    { word: "erreichen", meaning: "to achieve / reach", category: "verbs", type: "verb" },
    { word: "überlegen", meaning: "to consider / think over", category: "verbs", type: "verb" },
    { word: "verlassen", meaning: "to leave", category: "verbs", type: "verb" },
    { word: "anbieten", meaning: "to offer", category: "verbs", type: "verb" },
    { word: "vergleichen", meaning: "to compare", category: "verbs", type: "verb" },
    { word: "teilnehmen", meaning: "to participate", category: "verbs", type: "verb" },
    { word: "erkennen", meaning: "to recognize", category: "verbs", type: "verb" },
    { word: "bedeuten", meaning: "to mean", category: "verbs", type: "verb" },
    { word: "fehlen", meaning: "to be missing / to lack", category: "verbs", type: "verb" },
    { word: "kümmern", meaning: "to care for / look after", category: "verbs", type: "verb" },
    { word: "gehören", meaning: "to belong", category: "verbs", type: "verb" },
    { word: "streiten", meaning: "to argue", category: "verbs", type: "verb" },
    { word: "weinen", meaning: "to cry", category: "verbs", type: "verb" },

    // ===== ADJECTIVES =====
    { word: "gefährlich", meaning: "dangerous", category: "adjectives", type: "adjective" },
    { word: "vorsichtig", meaning: "careful", category: "adjectives", type: "adjective" },
    { word: "wichtig", meaning: "important", category: "adjectives", type: "adjective" },
    { word: "möglich", meaning: "possible", category: "adjectives", type: "adjective" },
    { word: "erfolgreich", meaning: "successful", category: "adjectives", type: "adjective" },
    { word: "zufrieden", meaning: "satisfied", category: "adjectives", type: "adjective" },
    { word: "verrückt", meaning: "crazy", category: "adjectives", type: "adjective" },
    { word: "streng", meaning: "strict", category: "adjectives", type: "adjective" },
    { word: "gemütlich", meaning: "cozy / comfortable", category: "adjectives", type: "adjective" },
    { word: "spannend", meaning: "exciting / thrilling", category: "adjectives", type: "adjective" },
    { word: "langweilig", meaning: "boring", category: "adjectives", type: "adjective" },
    { word: "mutig", meaning: "brave", category: "adjectives", type: "adjective" },
    { word: "stolz", meaning: "proud", category: "adjectives", type: "adjective" },
    { word: "seltsam", meaning: "strange / weird", category: "adjectives", type: "adjective" },
    { word: "leise", meaning: "quiet", category: "adjectives", type: "adjective" },

    // ===== ADVERBS =====
    { word: "besonders", meaning: "especially", category: "adverbs", type: "adverb" },
    { word: "wenigstens", meaning: "at least", category: "adverbs", type: "adverb" },
    { word: "deshalb", meaning: "therefore", category: "adverbs", type: "adverb" },
    { word: "hoffentlich", meaning: "hopefully", category: "adverbs", type: "adverb" },
    { word: "normalerweise", meaning: "normally", category: "adverbs", type: "adverb" },
    { word: "nirgends", meaning: "nowhere", category: "adverbs", type: "adverb" },
    { word: "überall", meaning: "everywhere", category: "adverbs", type: "adverb" },
    { word: "sofort", meaning: "immediately", category: "adverbs", type: "adverb" },
    { word: "plötzlich", meaning: "suddenly", category: "adverbs", type: "adverb" },
    { word: "schließlich", meaning: "finally / eventually", category: "adverbs", type: "adverb" },

    // ===== PREPOSITIONS =====
    { word: "wegen", meaning: "because of", category: "prepositions", type: "preposition" },
    { word: "trotz", meaning: "despite", category: "prepositions", type: "preposition" },
    { word: "während", meaning: "during", category: "prepositions", type: "preposition" },
    { word: "innerhalb", meaning: "inside of / within", category: "prepositions", type: "preposition" },
    { word: "außerhalb", meaning: "outside of", category: "prepositions", type: "preposition" },
    { word: "gegenüber", meaning: "opposite / across from", category: "prepositions", type: "preposition" },
    { word: "statt", meaning: "instead of", category: "prepositions", type: "preposition" },
    { word: "entlang", meaning: "along", category: "prepositions", type: "preposition" },
    { word: "neben", meaning: "next to", category: "prepositions", type: "preposition" },
    { word: "zwischen", meaning: "between", category: "prepositions", type: "preposition" },

    // ===== CONJUNCTIONS =====
    { word: "damit", meaning: "so that", category: "conjunctions", type: "conjunction" },
    { word: "ob", meaning: "whether / if", category: "conjunctions", type: "conjunction" },
    { word: "als", meaning: "when (in the past) / than", category: "conjunctions", type: "conjunction" },
    { word: "solange", meaning: "as long as", category: "conjunctions", type: "conjunction" },
    { word: "falls", meaning: "in case / if", category: "conjunctions", type: "conjunction" },
    { word: "entweder ... oder", meaning: "either ... or", category: "conjunctions", type: "conjunction" },
    { word: "weder ... noch", meaning: "neither ... nor", category: "conjunctions", type: "conjunction" },
    { word: "zwar ... aber", meaning: "indeed ... but", category: "conjunctions", type: "conjunction" },
    { word: "sowohl ... als auch", meaning: "both ... and", category: "conjunctions", type: "conjunction" },
    { word: "deswegen", meaning: "that's why", category: "conjunctions", type: "conjunction" }
];
